### ISSUE TITLE
希望自动回复功能能与外部Services对接

### ISSUE THREAD

**Issue by a272121742** [TKkk-iOSer/WeChatPlugin-MacOS#101]
例如图灵机器人、微软小娜、贤二机器人、白丝魔理沙等，自己设置自动回复还是太麻烦了，如果能接入外部智能对话机器人，会更有意思～

**Comment by ypwhs** [comment]
哇，那能实现的功能可不少呢，支持一个

**Comment by miniers** [comment]
这个需求自己改代码就很容易实现，作者的自动回复部分已经给足了例子

**Comment by TKkk-iOSer** [comment]
之前的话，有去调研图灵机器人，发现需要设置一些配置，然而界面上不知道如何设计，所以就没有加了，可以像上面 @miniers 所说的，自己尝试加下。
