### ISSUE TITLE
增加群助手功能

### ISSUE THREAD

**Issue by DeveloperPans** [TKkk-iOSer/WeChatPlugin-MacOS#104]
现在大家都有很多微信群，特别是工作群。有的群其实并不想看，但是又不能退，群消息非常频繁导致聊天列表页混乱。重要的消息容易被挤到下面去。能不能新增支持个群助手的功能？

**Comment by TKkk-iOSer** [comment]
感觉这个需求有点抽象，因为没有一个规则来判断什么是重要的消息。

**Comment by DeveloperPans** [comment]
我详细描述下，这个需求和目前的 「聊天置底」需求很像。 希望可以添加一个「群助手」，右键某个聊天，可以把聊天收入 群助手。点击群助手可以查看被收入群助手的聊天。被收入群助手的聊天不再再主界面显示。群助手本身也不会有数字红点。

**Comment by xiebruce** [comment]
对，这个我也很需要，微信官方是不是只有一个人在搞这个啊，都没你自己业余搞的快

**Comment by DeveloperPans** [comment]
@xiebruce 估计微信官方不打算上群助手功能

**Comment by xiebruce** [comment]
@DeveloperPans 因为这样做下去，感觉功能会趋向于QQ，无法差异化了，QQ的功能比微信多的多，为什么现在的人都喜欢用微信，我就奇了怪了

**Comment by TKkk-iOSer** [comment]
懂你的意思了，其实微信是在做限制吧，不想要有太多的功能。（@xiebruce ~~PS: 最近也忙了，没啥时间折腾这个了~~）

**Comment by xiebruce** [comment]
@TKkk-iOSer 辛苦辛苦，能修复一下批量删除闪退的bug吗？这个功能你加了但是没法用，怪可惜的

**Comment by TKkk-iOSer** [comment]
@xiebruce 批量删除闪退？我的倒是不会，是只删除好友就闪退么？还是说有删除公众号之类的

**Comment by xiebruce** [comment]
@TKkk-iOSer 就是删除正在聊天的好友呀，没有删除公众号之类的，这个功能还是我提出来的呢，就是微信没法批量删除正在聊天的好友，所以让你加了，但是我用的时候就程序崩溃，就算我只选两个人也崩溃
