### ISSUE TITLE
功能已经很完美了！再加上这两个功能就更牛逼了！

### ISSUE THREAD

**Issue by xieao100** [TKkk-iOSer/WeChatPlugin-MacOS#105]
1、保存助手配置，每次升级都要重新配置一遍指令，自动回复关键字，为何不做个配置文件保存下来呢？
2、红包提示功能，不说抢红包了，单纯就是红包来了 给个提示，方便大家拿出手机来抢。
如此，岂不美哉。
辛苦了，大神！

**Comment by TKkk-iOSer** [comment]
这个想法不错，你 `MADAO` 的昵称也不错.
