### ISSUE TITLE
只显示/弹出指定人信息

### ISSUE THREAD

**Issue by NominationP** [TKkk-iOSer/WeChatPlugin-MacOS#107]
在菜单栏,任何消息都会显示红点
有什么办法可以指定特定联系人(比如老板) 的信息就会提示,其他人都不显示.
可以节省很多精力

**Comment by NominationP** [comment]
@TKkk-iOSer 我没接触过这方面,想知道我说的这个功能是否有实现的可能性

**Comment by wendingp** [comment]
所以才有置底这个功能...

**Comment by TKkk-iOSer** [comment]
@wendingp 有道理。
