### ISSUE TITLE
免认证登录 能不能改成 一打开微信就自动登录了, 而不需要点击登录再登录

### ISSUE THREAD

**Issue by liangnaisong** [TKkk-iOSer/WeChatPlugin-MacOS#109]

**Comment by TKkk-iOSer** [comment]
这个之前有人提过，个人认为使用 Spotlight 启动微信再按下回车也挺快的hhhhh  https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/80

**Comment by TKkk-iOSer** [comment]
由于新版点击回车没法登录了，因此在登录界面新增自动登录的选项，请享用🙃
