### ISSUE TITLE
添加定时回复

### ISSUE THREAD

**Issue by IronLung7** [TKkk-iOSer/WeChatPlugin-MacOS#11]
可是生日祝福的利器

**Comment by VinceFanZ** [comment]
小伙子你这样没诚意的 [奸笑]

**Comment by IronLung7** [comment]
的确诚意不够， 那就再加个和日历集成，省的自己设时间了 :)

**Comment by TKkk-iOSer** [comment]
是不是还要搞个聊天机器人 😂😂😂

定时自动回复？是定时开启该功能么，还是说定时自动发送给特定好友消息？

**Comment by haoxuexiaoyao** [comment]
弄个接口么可以，定时获取里面的内容发消息给好友或者群？
