### ISSUE TITLE
哇，我又来了，突然大伙很需要一个很重要的功能(Mac用户通病)

### ISSUE THREAD

**Issue by new88888** [TKkk-iOSer/WeChatPlugin-MacOS#110]
清理缓存能不能有= =因为微信的表情包特吃资源，这个功能可以直接加个入口 点了之后然后执行命令：

`rm -rf ~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/****/Stickers`

PS: ****为用户的微信目录

妈耶。刚才清理出几G表情包等无用的垃圾文件= =硬盘瞬间轻松了。。。。有毒

**Comment by TKkk-iOSer** [comment]
厉害了，我之后加上，也看下是否会有删除其他资源的隐患。

**Comment by wendingp** [comment]
orz
