### ISSUE TITLE
免认证登录无法正常工作

### ISSUE THREAD

**Issue by kimpeng** [TKkk-iOSer/WeChatPlugin-MacOS#111]
免认证登录后直接秒出退出弹窗，无法登录。

**Comment by TKkk-iOSer** [comment]
请问扫码登录之后下次登录还是一样无法正常工作么？是否有在手机上退出微信过？

**Comment by kimpeng** [comment]
扫码登录之后把免认证登录开启，然后退出重新打开后点击登录按钮，接着Label字样变成免认证登录中，马上就弹出微信已退出。

**Comment by TKkk-iOSer** [comment]
必现是么？请问是否有更新微信？手机端的微信是否有退出过？ 一般无法免认证登录的原因有两个：1.之前扫码的手机端微信退出。2.mac的微信登录的key过期。

**Comment by sqzxcv** [comment]
@TKkk-iOSer 手机退出，mac 是不是必须退出，能否做到：手机退出，mac 任然保持登录呢？

**Comment by TKkk-iOSer** [comment]
@kimpeng 已修复 @sqzxcv 没办法，手机退出，mac端应该就退出了，我之前试的是这样，不知道现在有没有变了
