### ISSUE TITLE
批量删除当前聊天用户崩溃

### ISSUE THREAD

**Issue by xiebruce** [TKkk-iOSer/WeChatPlugin-MacOS#112]
我多选后右键选择删除，直接程序崩溃退出了
微信：Version. 2.3.5 (9814)
系统：macOS High Sierra 10.13.1 (17B48)

我已更新到你的最新版本：
~/Softwares/WeChatPlugin-MacOS/Other(master) # git pull
Already up-to-date.

**Comment by TKkk-iOSer** [comment]
每次都会崩溃么？是否有选中了公众号之类的？重新clone会么？

**Comment by xiebruce** [comment]
@TKkk-iOSer 我试了重新clone重新覆盖安装，还是一样的问题，我没有选中公众号，就选的聊天的好友，只要多选然后右键删除，就会崩溃，哪怕我哪选两个也会，你那不会么？是不是跟macos系统版本有关系？

**Comment by TKkk-iOSer** [comment]
已修复，微信2.3.5中的对象 `MMSessionInfo` 去掉了` WCContactData` 对象导致的闪退。
