### ISSUE TITLE
Bug: Always on top function will cause setting button not functioning

### ISSUE THREAD

**Issue by legendtang** [TKkk-iOSer/WeChatPlugin-MacOS#113]
After enabling always on top functioning, the setting button at left bottom corner will not work.

**Comment by legendtang** [comment]
Wrong issue. Sorry.

**Comment by TKkk-iOSer** [comment]
ok, I will fix it on my free time, thanks for your feedback.

**Comment by TKkk-iOSer** [comment]
Fixed.
