### ISSUE TITLE
能否在Addmsg 中获取微信用户的nickname

### ISSUE THREAD

**Issue by dennykong** [TKkk-iOSer/WeChatPlugin-MacOS#120]
能否在Addmsg 中获取微信用户的nickname

**Comment by dennykong** [comment]
已解决，在
WCContactData 添加
@property (nonatomic, copy) NSString *m_nsNickName;

**Comment by dennykong** [comment]
@lichongsw 如果是好友，能拿到username，肯定可以拿到nickname的
    WCContactData *msgContact = [contactStorage GetContact:addMsg.fromUserName.string];
    NSString *nickName=msgContact.m_nsNickName;
    NSLog(@"m_nsNickName:%@",nickName);
群的话，不知道是否能通过WCContactData 获得非好友

**Comment by lichongsw** [comment]
@dennykong 嗯，确实你的示例代码能够拿到好友的nickname。我的需求是拿到群聊中发言的人的nickname，就是不知道哪个数据结构中有这个属性。可以重开issue不，看看楼主大人对于群聊的人的nickname是什么建议。谢谢啦！

**Comment by JasperYanky** [comment]
[MessageData groupChatSenderDisplayName] 
@lichongsw
