### ISSUE TITLE
每次开机都需要重新运行 Install.sh 才能生效吗

### ISSUE THREAD

**Issue by wuyukai879293** [TKkk-iOSer/WeChatPlugin-MacOS#123]
系统 MacOS Sierra 版本10.12.6
每次重启后微信就恢复原样，需要重新运行 install.sh 才能出现微信小助手。
不知是个人原因还是没有普遍情况？

**Comment by TKkk-iOSer** [comment]
本人倒是没遇到过…

**Comment by wuyukai879293** [comment]
全部卸载重新装后这几天没问题了，谢谢啦！之前可能是电脑抽疯，关闭吧。
