### ISSUE TITLE
mac上如何调式？

### ISSUE THREAD

**Issue by sanshanchuns** [TKkk-iOSer/WeChatPlugin-MacOS#132]
mac上如何调式？

**Comment by TKkk-iOSer** [comment]
这是如何搭建调试环境[macOS逆向-微信小助手](http://www.tkkk.fun/2017/04/21/macOS%E9%80%86%E5%90%91-%E5%BE%AE%E4%BF%A1%E5%B0%8F%E5%8A%A9%E6%89%8B/ )，调试的话，类似iOS，直接在xcode上调试。

**Comment by sanshanchuns** [comment]
谢谢

备注一下

Edit Scheme  编辑 Run --> Info 
Executable -> 选择 Ask on Launch 选 wechat.app

**Comment by sanshanchuns** [comment]
谢谢

备注一下

Edit Scheme  编辑 Run --> Info 
Executable -> 选择 Ask on Launch 选 wechat.app

**Comment by sanbad0x** [comment]
赞同@sanshanchuns 初学者是不懂如何调试的，楼主也确实没写清楚@TKkk-iOSer
