### ISSUE TITLE
macOS weChat Version. 2.3.6 (10159)

### ISSUE THREAD

**Issue by s2339956** [TKkk-iOSer/WeChatPlugin-MacOS#136]
cp: /Applications/WeChat.app/Contents/MacOS/WeChat_backup: Permission denied
cp: /Applications/WeChat.app/Contents/MacOS/WeChatPlugin.framework: Permission denied
/Applications/WeChat.app/Contents/MacOS/WeChat_backup: No such file or directory

新版的 weChat 找不到這幾個檔案了 ?!

**Comment by TKkk-iOSer** [comment]
无权限，执行下`sudo chown -R $(whoami) /Applications/WeChat.app`

**Comment by s2339956** [comment]
OK，已解決，謝謝

**Comment by qierkang** [comment]
还是不行啊，求助 求助
<img width="1704" alt="image" src="https://user-images.githubusercontent.com/17940151/226873393-911a3b6f-d530-4032-ac3f-816066e43c4a.png">
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/17940151/226873478-187fe014-552f-4483-aad5-2fb65869a5cb.png">
