### ISSUE TITLE
反馈下微信升级2.3.6 10159以后遇到的问题

### ISSUE THREAD

**Issue by DrawLi** [TKkk-iOSer/WeChatPlugin-MacOS#137]
系统10.11.6
已更新git代码，1月7日20点50分

自动登录正常。登录以后只显示了3个聊天对象，应该是最近3个聊过天的好友。
a、在对话框界面的搜索，搜不到任何这3个外的好友；
b、通讯录搜索不到任何好友，包括这3位；
c、这时候在手机打开下微信，手机提示MAC已登录，以前有过对话的好友就能刷新出来，目测顺序随机。但是在通讯录还是搜不到任何好友。

**Comment by TKkk-iOSer** [comment]
免认证导致的(2.3.6部分方法实现更改导致)，已修复。
