### ISSUE TITLE
部分好友不会自动回复

### ISSUE THREAD

**Issue by feepees** [TKkk-iOSer/WeChatPlugin-MacOS#140]
if (msgContact.m_uiFriendScene == 0 && ![addMsg.fromUserName.string containsString:@"@chatroom"])//这个判断是公众号貌似不太准确，有部分联系人msgContact.m_uiFriendScene这个字段也是为0的，想问一下这个字段是什么意思？？？

**Comment by TKkk-iOSer** [comment]
之前 iOS 端的有这个字段的判断，以为就一样了，后来发现不一样，已修复。
