### ISSUE TITLE
刚刚安装好微信小助手 我的微信就打不开了

### ISSUE THREAD

**Issue by BoYaoEssex** [TKkk-iOSer/WeChatPlugin-MacOS#143]
刚刚安装好微信小助手 我的微信就打不开了
问题表现为 点击（打开）微信没反应  什么也没打开  等了很久都一样
mac下
重启mac也不行

**Comment by s2339956** [comment]
請移除 助手 重裝試試？

**Comment by TKkk-iOSer** [comment]
@BoYaoEssex 卸载重新安装试试
