### ISSUE TITLE
请问能否实现将撤回内容发送到文件传输助手？

### ISSUE THREAD

**Issue by Sev73n** [TKkk-iOSer/WeChatPlugin-MacOS#146]
每个人的微信都有一个同名的微信号 也可以用来当作文件传输
这样点开同名的微信号就是撤回内容
文件传输助手也可以照旧使用 用作电脑内容传输

如果能实现 也就变相的实现了 免越狱手机查看消息防撤回

**Comment by xieao100** [comment]
那就必须要开着电脑了！现在也挺好，想看撤回消息直接在电脑上看就好了！

**Comment by Sev73n** [comment]
是的！因为我是一直开着电脑的，这样在外面的时候手机也能看到防撤回的，不用非远程登录电脑查看了

**Comment by keepyounger** [comment]
把下面的代码放到 WeChat+hook.m 315行左右
`        [msgService SendTextMessage:currentUserName toUsrName:@"filehelper" msgText:newMsgContent atUserList:nil];
`

**Comment by Sev73n** [comment]
感谢作者真的做了！但是我的操作好像哪里出问题了，无法成功编译
![2018-02-28 at 17 09](https://user-images.githubusercontent.com/16495885/36776716-2e80f6c2-1caa-11e8-99c7-be7c12397a0c.png)

**Comment by keepyounger** [comment]
@Sev73n 查看你的 WeChatPlugin.h 45行左右 看看是不是下面的 或者 你更新一下工程看看

> `- (void)onRevokeMsg:(id)arg1;`
> `- (void)OnSyncBatchAddMsgs:(NSArray *)arg1 isFirstSync:(BOOL)arg2;`
> `- (id)SendTextMessage:(id)arg1 toUsrName:(id)arg2 msgText:(id)arg3 atUserList:(id)arg4;`
> `- (id)GetMsgData:(id)arg1 svrId:(long)arg2;`
> `- (void)AddLocalMsg:(id)arg1 msgData:(id)arg2;`

**Comment by Sev73n** [comment]
已经成功实现文字撤回信息转发到文件传输助手！虽然图片等多媒体还没法转发，但是非常感谢开发者！
