### ISSUE TITLE
禁用微信自动更新

### ISSUE THREAD

**Issue by peteve** [TKkk-iOSer/WeChatPlugin-MacOS#148]
有没有办法增加一个微信自动更新开关，因为有时候app的更新会导致插件失效。

**Comment by s2339956** [comment]
如果是透過 app store 安裝 可以設置電腦的更新 來限制是否更新

**Comment by lmk123** [comment]
为了避免自动更新让插件失效，我写了这个，你可以试试 https://github.com/lmk123/oh-my-wechat

**Comment by TKkk-iOSer** [comment]
@peteve  如@s2339956 所说， 一般来说可以在偏好设置里面设置 App Store 防止自动更新。(@lmk123 厉害了，回头看下)
