### ISSUE TITLE
希望添加英文显示

### ISSUE THREAD

**Issue by ahonn** [TKkk-iOSer/WeChatPlugin-MacOS#151]
如果能够根据系统语言显示 中/英文 的话会比较好。

目前在英文语言下，menu 以及其他的显示均为中文，看起来很蛋疼。

![](http://ouv0frko5.bkt.clouddn.com/blog/i9xyn.jpg)

**Comment by tomaer** [comment]
我也是非常支持的.希望添加国际化

**Comment by TKkk-iOSer** [comment]
ok，之后加上

**Comment by TKkk-iOSer** [comment]
Fixed
