### ISSUE TITLE
非常希望能加入自动邀请入群功能

### ISSUE THREAD

**Issue by Sunbelife** [TKkk-iOSer/WeChatPlugin-MacOS#153]
感谢作者的努力，工具现在支持群聊正则自动回复非常不错。
但很希望能加入自动邀请入群功能，这样就能代替基于 Web 的微信群机器人了，希望能得到回复。
谢谢。

**Comment by Sunbelife** [comment]
顺便提交一个 Bug，自动回复功能似乎只能在当前窗口回复消息，如果被艾特的群不是当前的窗口，自动回复的消息就会错发到当前窗口了。

**Comment by TKkk-iOSer** [comment]
自动邀请入群？我觉得日常使用中好像很少用到这个。(其实还是不想做成类似web的微信群机器人，只是想在日常使用中提高效率)

**Comment by lly835** [comment]
我也想提这个需要，邀请加入群聊。解放运营人员的双手🙌
