### ISSUE TITLE
希望能将撤回的消息转发到文件传输助手

### ISSUE THREAD

**Issue by laravelup** [TKkk-iOSer/WeChatPlugin-MacOS#154]
希望能将撤回的消息转发到文件传输助手

**Comment by keepyounger** [comment]
把下面的代码放到 WeChat+hook.m 315行左右 然后自己重新编译
`        [msgService SendTextMessage:currentUserName toUsrName:@"filehelper" msgText:newMsgContent atUserList:nil];
`

**Comment by TKkk-iOSer** [comment]
@keepyounger 厉害了

**Comment by keepyounger** [comment]
@TKkk-iOSer 群聊的只是不显示那个群名称 初步观察其他是正常的

**Comment by TKkk-iOSer** [comment]
@keepyounger 是的，就是没有显示是哪个群聊，这个得要再去找下了
