### ISSUE TITLE
是否支持最新版本的微信 for Mac

### ISSUE THREAD

**Issue by Thor1992** [TKkk-iOSer/WeChatPlugin-MacOS#157]
咱们的插件对于最新版本的支持，有什么需要注意的地方吗？

**Comment by TKkk-iOSer** [comment]
支持，如果出现什么问题可以提 issue，其他一些细节的可以看 readme.md，例如想远程控制网易云需要在辅助功能添加微信权限等等。

**Comment by TKkk-iOSer** [comment]
@langzc520 看下是否有装git，没有的话按照普通安装来安装，注意在终端运行脚本的时候要输入 macbook 的密码，还有，输入的时候是不显示密码的。
