### ISSUE TITLE
防撤回功能显示问题

### ISSUE THREAD

**Issue by andyliu24** [TKkk-iOSer/WeChatPlugin-MacOS#158]
虽然保留别人撤回的消息，但有时候自己也有需要撤回消息。
一旦忘记关闭防撤回，点击一次撤回后，再关闭防撤回功能并撤回消息，会一直表现为消息未发出的样式。

![123](https://user-images.githubusercontent.com/24978668/35763707-d88647c0-08ec-11e8-8fe1-8ea0c8da014d.png)

刚刚看了一下，他人的设备上确实消息已经撤回。: )

**Comment by TKkk-iOSer** [comment]
已修复，请`git clone`再试试。
