### ISSUE TITLE
微信长时间运行后崩溃

### ISSUE THREAD

**Issue by lichongsw** [TKkk-iOSer/WeChatPlugin-MacOS#162]
@TKkk-iOSer 
插件功能使用和体验非常好。就是在特定情况下稳定性不够，应该与自己后来添加的代码和使用场景有关系。基本上连续运行3天左右微信进程会崩溃掉，也有可能是消息负载的问题。

能不能麻烦您百忙之中抽空看看这个问题指点一二，非常感谢！
程序崩溃日志：
[wechat_crash.zip](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/files/1701979/wechat_crash.zip)

**Comment by iszhuzhi** [comment]
同上！点击查看群或者消息的图片，也会崩溃闪退！！

**Comment by TKkk-iOSer** [comment]
你们是都升到了2.3.10了么

**Comment by iszhuzhi** [comment]
哦买嘎，我是耶，【2.3.10】微信版本，稳定性不是很乐观，没安全感；

1.习惯性点开别人发的图，直接闪退；
2.长时间使用，未操作也会崩溃。

**Comment by lichongsw** [comment]
我的版本是2.3.7，也是担心稳定性一直没有升级版本。目前来说基本上可以用3天才奔溃一次，尚处于可以维护的范围内。

**Comment by TKkk-iOSer** [comment]
我倒是没遇到过，可以尝试卸载小助手看看。我看了下 App Store 官方的评论，好像有说偶尔会闪退。有可能是官方的问题。另外崩溃日志的话看不了…因为我这边也没有微信的 dSYM 文件…所以没办法符号化。

**Comment by s2339956** [comment]
我使用 Version. 2.3.9 (10177) 貌似也沒遇見閃退問題....

**Comment by TKkk-iOSer** [comment]
优化了部分代码，重新安装下试试
