### ISSUE TITLE
可以考虑带上检查更新的功能

### ISSUE THREAD

**Issue by Cat7373** [TKkk-iOSer/WeChatPlugin-MacOS#165]
可以在编译时带上当前`commit`的`hash`，然后来`github`比对是不是最新的 0.0

**Comment by smusicsanshu** [comment]
借楼问一下，如何手动更新呢？直接覆盖安装？

**Comment by Cat7373** [comment]
没试过，不过先卸载再安装应该可以吧。。

**Comment by TKkk-iOSer** [comment]
@Cat7373  之前有人提过，下一版再加上。
@smusicsanshu 直接覆盖安装就行了，可以不用卸载。

**Comment by TKkk-iOSer** [comment]
已更新 👏👏👏 @Cat7373

**Comment by Cat7373** [comment]
emmm 保存表情的功能不错，然而 GIF 图存下来就成惹 jpg 后缀😂

**Comment by TKkk-iOSer** [comment]
居然比我还强迫症  ![](http://ws1.sinaimg.cn/bmiddle/9150e4e5ly1fj6hybhp60j203o046dgi.jpg)

**Comment by TKkk-iOSer** [comment]
已解决 👏🏻👏🏻👏🏻 @Cat7373

**Comment by Cat7373** [comment]
噗，首字节😂

**Comment by TKkk-iOSer** [comment]
被发现了… ![](http://wx1.sinaimg.cn/bmiddle/006Cmetyly1fn3rwl6rzkj305i05cdgd.jpg)
