### ISSUE TITLE
插个楼，如果能自动抢红包，那该多好。。。

### ISSUE THREAD

**Issue by williamzid** [TKkk-iOSer/WeChatPlugin-MacOS#167]
是不是想的有的歪了。。。。

**Comment by TKkk-iOSer** [comment]
那不行，会没朋友

**Comment by williamzid** [comment]
哈哈哈，可以实现是么。。。

**Comment by TKkk-iOSer** [comment]
应该可以，比较麻烦就是了，别(wo)干(jiu)坏(shi)事(lan)

**Comment by EveDreamer** [comment]
这玩意儿用不好是会被封号的……


原始邮件
发件人:williamzidnotifications@github.com
收件人:TKkk-iOSer/WeChatPlugin-MacOSWeChatPlugin-MacOS@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年2月27日(周二) 16:50
主题:Re: [TKkk-iOSer/WeChatPlugin-MacOS] 插个楼，如果能自动抢红包，那该多好。。。 (#167)


哈哈哈，可以实现是么。。。

**Comment by Cat7373** [comment]
感觉一旦加这个功能，被微信官方发现，就可能会下大力气检测这种插件 😂

**Comment by tanranran** [comment]
wocao

实现的原理是什么

非常好奇

**Comment by TKkk-iOSer** [comment]
@tanranran 原理：https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/3
