### ISSUE TITLE
最新版微信点击远程控制崩溃

### ISSUE THREAD

**Issue by keepyounger** [TKkk-iOSer/WeChatPlugin-MacOS#168]
微信版本号Version. 2.3.10 (10339)

找到原因了：TKRemoteControlCommands.plist这个文件不知道为啥不存在，手动copy到TKWeChatPlugin目录就好了

**Comment by TKkk-iOSer** [comment]
你所说的文件不存在指的是在哪个路径下的？沙盒路径么？

**Comment by keepyounger** [comment]
Users下的，应该是我的问题
