### ISSUE TITLE
希望增加窗口切换快捷键

### ISSUE THREAD

**Issue by haoxuexiaoyao** [TKkk-iOSer/WeChatPlugin-MacOS#169]
你好,可以增加多个微信快捷键切换么,习惯快捷键了

**Comment by haoxuexiaoyao** [comment]
谢谢啊

**Comment by TKkk-iOSer** [comment]
你提过了，也有人给出了解决方案。https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/116 目前还未想到其他的方法

**Comment by haoxuexiaoyao** [comment]
你好,给出的方案是 app 有那个快捷键功能的才可以,因为微信本身不支持多个同时登陆,没有提供那个快捷键,两个微信的时候,聊天窗口切换麻烦,就是希望能提供 cmd + ` 这个快捷键

**Comment by haoxuexiaoyao** [comment]
@TKkk-iOSer 希望支持个快捷键切换的哈 谢谢啊
