### ISSUE TITLE
聊天的历史记录没了

### ISSUE THREAD

**Issue by Xunqf** [TKkk-iOSer/WeChatPlugin-MacOS#17]

**Comment by TKkk-iOSer** [comment]
是会有这个问题，因为加这个插件就相当于创建了一个新的app，所以聊天记录会没掉，如果想找回的话可以先卸载，执行 `./Other/Uninstall.sh`

**Comment by Xunqf** [comment]
如果能合并就好了

**Comment by XYScience** [comment]
同上，不知道可不可以合并聊天记录呢？

**Comment by TKkk-iOSer** [comment]
@Xunqf @XYScience 已修复

**Comment by XYScience** [comment]
修复的原理是什么啊？

**Comment by TKkk-iOSer** [comment]
@XYScience 沙盒的位置改了，所以 hook 了带有 `NSSearchPathForDirectoriesInDomains` 的方法，将 `NSDocumentDirectory` 与 `NSLibraryDirectory`的路径重新指向原先的路径。不愧是鹅厂，方法封装的真好。

**Comment by XYScience** [comment]
@TKkk-iOSer 还是不可以合并聊天记录啊。而且修改后，iCloud Drive里的文稿文件夹多里一个MMappedKV的文件夹啊～～

**Comment by TKkk-iOSer** [comment]
因为目录指向了之前的路径，所以期间的聊天记录就没了，会恢复到之前微信原版的聊天记录。另外 iCloud Drive 的那个文件夹是删掉之后又出现的么？

**Comment by XYScience** [comment]
原版是指第一次安装的微信版本吗？删掉之后是又回出现，好像会根据聊天信息变化

**Comment by TKkk-iOSer** [comment]
@XYScience 就是恢复成未安装插件的样子， iCloud Drive 我这边是一直没有出现这个文件…无论有没有修复这个问题。去 iCloud Drive设置看下是否有选中什么东西。
