### ISSUE TITLE
电脑卡死

### ISSUE THREAD

**Issue by charsdavy** [TKkk-iOSer/WeChatPlugin-MacOS#171]
插件用久了之后电脑会因为微信而卡死，测试过不使用该插件则没有卡死问题。希望能够排查一下是否有内存泄露的问题。

**Comment by zhuSilence** [comment]
我这边偶尔也会卡死

**Comment by TKkk-iOSer** [comment]
我倒是没出现过这样的情况…之后跟进一下

**Comment by Cat7373** [comment]
没找到 @TKkk-iOSer 做的 QQ 版，于是在 Github 找了另一个人做的，然后每次一点语音消息，QQ 100%卡死，只能强杀 😂

微信这个倒是没遇到过什么问题。。

**Comment by TKkk-iOSer** [comment]
优化了部分逻辑，重新安装下试试
