### ISSUE TITLE
防撤回功能可以添加包括非文本的吗？

### ISSUE THREAD

**Issue by dongjunjie** [TKkk-iOSer/WeChatPlugin-MacOS#172]
![2018-03-01 3 37 31](https://user-images.githubusercontent.com/10395782/36832455-7ecf0242-1d66-11e8-9096-dcd0acc37e45.png)

**Comment by TKkk-iOSer** [comment]
可以提示是什么类型的，但是没办法显示出来，比如说是一张图片，没办法显示撤回图片的内容，只能提示说撤回了图片就是了

**Comment by dongjunjie** [comment]
提供一个思路：
搜了一下，微信会将所有图片存在类似
~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/***/Message/MessageTemp/***/Image
这样的目录中，一个是原图，一个是缩略图。
是否可以监听这个文件夹的变化，然后定时复制出来？
这样通过对比就可以大致知道撤回什么图片了?

**Comment by dongjunjie** [comment]
说实话，很多老司机群，撤回的都是图片。这个需求应该还是很大的

**Comment by TKkk-iOSer** [comment]
已更新代码。增加撤回的用户昵称 & 消息类型。
个人觉得监听这个文件夹的成本有点大。而且其实防撤回了一般都能自己识别是撤回哪个消息，除非是同时多个同样的消息类型，不过这时候只要打开手机端看下就知道了。
