### ISSUE TITLE
使用锁屏指令后开启时无法输入密码

### ISSUE THREAD

**Issue by zhanggang807** [TKkk-iOSer/WeChatPlugin-MacOS#173]
RT
macos version 10.13.3
wechat version 2.3.10
plugin version 最新版

**Comment by TKkk-iOSer** [comment]
无法输入密码？必现么？是否是输入法的原因？我这边都没遇到过。

**Comment by Cifer-Y** [comment]
哇，这是什么操作，我今天刚用了这个功能，没遇到这个问题

**Comment by TKkk-iOSer** [comment]
@zhanggang807 感觉是个别机型跟本身的设置冲突了吧，建议使用屏幕保护指令，再设置个开启屏保5s后锁屏，这样会更好点，而且还不用输入账号
