### ISSUE TITLE
自己撤回消息也拦截了

### ISSUE THREAD

**Issue by ttttmr** [TKkk-iOSer/WeChatPlugin-MacOS#178]
如图，自己撤回的不用拦截吧😂
![screenshots](https://user-images.githubusercontent.com/32825326/36964538-ecd0cd74-2091-11e8-966a-689fc592c0dc.png)

**Comment by TKkk-iOSer** [comment]
我还以为会有人跟我一样，忘了自己撤回什么内容，所以就把自己的也给拦截了…所以就我一个人这么认为么😂

**Comment by moonfruit** [comment]
@TKkk-iOSer 可以保留自己撤回记录，但是要真的撤回消息撒

**Comment by TKkk-iOSer** [comment]
@moonfruit 撤回是有撤回的，虽然上面显示拦截。

**Comment by ttttmr** [comment]
@TKkk-iOSer 嗯撤是真的撤回了，虽然我觉得不需要把自己的记录留着😂

**Comment by moonfruit** [comment]
@TKkk-iOSer 所以拦截自己消息的提示信息是不是换一换？

**Comment by TKkk-iOSer** [comment]
@moonfruit 已调整
