### ISSUE TITLE
hook微信的转发消息函数后客户端会崩溃？

### ISSUE THREAD

**Issue by kobe1941** [TKkk-iOSer/WeChatPlugin-MacOS#179]
如题，微信转发消息的函数是 MessageService的一个对象方法：
- (id)ForwardMessage:(id)arg1 toUser:(id)arg2 errMsg:(id)arg3;

对其进行hook后，点击转发客户端立即崩溃，不hook这个函数则没问题。

hook函数：
![image](https://user-images.githubusercontent.com/7099017/37017525-e8381a14-214b-11e8-8fff-7877f032bed3.png)

崩溃截图如下：
![image](https://user-images.githubusercontent.com/7099017/37017346-53c3c982-214b-11e8-8932-7d3770cda232.png)

大神求破？

**Comment by TKkk-iOSer** [comment]
该方法有返回值，而你写的 hook 返回的是  void

**Comment by kobe1941** [comment]
设置该函数的返回值为id，依然会崩溃额

![image](https://user-images.githubusercontent.com/7099017/37081470-81d06c70-2224-11e8-91d8-7da4a5db22d7.png)

**Comment by TKkk-iOSer** [comment]
`- (id)ForwardMessage:(id)arg1 toUser:(id)arg2 errMsg:(id *)arg3`,参数类型出错
