### ISSUE TITLE
最新版本的问题

### ISSUE THREAD

**Issue by lilovexin** [TKkk-iOSer/WeChatPlugin-MacOS#18]
系统版本：版本 10.12.6（版号 16G29）
系统语言：zh-Hans
微信版本：Version. 2.3.0 (9359)  v2.3.0.16 (0x12030010) #1879d7e8f
微信语言：zh-Hans
历史版本：[2017-06-19 14:02:56.242] Version. 2.2.8 (8578)  v2.2.8.16 (0x12020810) #bd5186f8c

之前的版本插件可以使用，今天更新以后插件消失，再次build的时候出现以下错误信息
错误信息：
cp: /Applications/WeChat.app/Contents/MacOS/WeChat_backup: Permission denied
cp: /Applications/WeChat.app/Contents/MacOS/WeChatPlugin.framework: Permission denied
/Applications/WeChat.app/Contents/MacOS/WeChat_backup: No such file or directory

**Comment by TKkk-iOSer** [comment]
跟之前的一样，微信需要重新赋予权限，或者更改owner。因为更新之后，微信的权限就恢复成默认了。
`sudo chown -R $(whoami) /Applications/WeChat.app`。

**Comment by TKkk-iOSer** [comment]
或者直接执行`./Other/Install.sh`就行了，我写成脚本了。
