### ISSUE TITLE
置顶微信窗口后有些弹出菜单之类的也被挡住了

### ISSUE THREAD

**Issue by xiaochunjimmy** [TKkk-iOSer/WeChatPlugin-MacOS#180]
置顶微信窗口后（快捷键⌘D）：
点击左下角的菜单按钮，无法弹出菜单，后来发现是被窗口挡住了；
点击设置，无法弹出设置界面，后台发现其实也弹出了，被微信窗口挡住了...
其他类似情况

**Comment by TKkk-iOSer** [comment]
是的，确实有这个问题，之前有人提过。之后修复下

**Comment by TKkk-iOSer** [comment]
已修复，请重新 `git clone`

**Comment by legendtang** [comment]
还有一个问题，视频窗口并无置顶，导致聊天窗口在视频窗口前

**Comment by TKkk-iOSer** [comment]
@legendtang 视频窗口你说的是跟别人视频聊天的窗口还是普通的视频播放的窗口？然后点击了这个视频窗口还是不能在前面么？

**Comment by legendtang** [comment]
@TKkk-iOSer 对的，依然不能，这个窗口没有被置顶，和微信主窗口不是一个 view

**Comment by TKkk-iOSer** [comment]
奇怪，刚刚我点击了是可以的。你是先置顶再打开视频，还是说先打开视频在制定的？

**Comment by TKkk-iOSer** [comment]
要不先卸载在重新安装试试

**Comment by legendtang** [comment]
@TKkk-iOSer 更新了 ok 了打扰了

**Comment by TKkk-iOSer** [comment]
@legendtang 恩恩，那就好
