### ISSUE TITLE
能否增加朋友圈功能。。。

### ISSUE THREAD

**Issue by i65181597** [TKkk-iOSer/WeChatPlugin-MacOS#183]
这个插件已经让我觉得大神牛B哄哄了，能否再加个刷朋友圈的功能。

**Comment by Chandler-Lu** [comment]
再怎么写也只是通过修改或劫持现有代码来实现某种功能。。作者总不可能凭空写出来一个朋友圈吧。。腾讯根本就没有开发mac端的朋友圈

**Comment by TKkk-iOSer** [comment]
@Chandler-Lu 其实可以去分析iOS上面的代码来实现，之前有人做过，不过那个人删库了，也没更新了，因此只能在旧版本中使用。所以， @i65181597 有点麻烦应该不考虑😂
