### ISSUE TITLE
微信置顶 闪退bug。

### ISSUE THREAD

**Issue by chenony** [TKkk-iOSer/WeChatPlugin-MacOS#187]
选择置顶后，然后在点击最小化， 微信自动最小化程序坞上，再次点击程序坞上的微信，然后微信闪退，打不开，必须强制退出微信再次登录才能使用。还有微信置顶快捷键容易误触，建议增加成三个按键。

**Comment by TKkk-iOSer** [comment]
ok,复现了，之后再跟一下

**Comment by chenony** [comment]
修改置顶的这个快捷键在多少行，我这个鼠标双指划过就是Command+d 很容触碰到置顶快捷键，然后出现这个bug，请问一下，修改置顶的快捷键，在那一行。

**Comment by TKkk-iOSer** [comment]
`WeChat+hook.m `,107行

**Comment by chenony** [comment]
改完，完，重新覆盖安装，不生效是哪里没有注意到

**Comment by TKkk-iOSer** [comment]
用 Xcode `bulid` 一下，然后 `run`，这时候会启动微信。 然后重启微信就行了。
或者执行`build`之后在执行 Other 中的`install`

**Comment by TKkk-iOSer** [comment]
已修复，快捷键也改了。
