### ISSUE TITLE
没有人发现大bug吗?

### ISSUE THREAD

**Issue by windiws** [TKkk-iOSer/WeChatPlugin-MacOS#188]
安装完成后,聊天记录都没了

**Comment by TKkk-iOSer** [comment]
1. 请打开`微信-偏好设置`，查看是否有勾选`退出时保留聊天记录`。
2. 手机端登录 mac 界面查看是否勾选 `登录后同步最近消息到 Mac`。
3. 勾选两者之后重启微信。
4. 还是不行的话重装小助手。

**Comment by windiws** [comment]
一直都有开保留聊天记录的,主要是安装插件后,原来微信的app的被备份,替换了插件那个新的app,就导致了记录不在,插件我没删除,但把wechat替换回来了,聊天记录还在,可是插件不在了

**Comment by windiws** [comment]
可以加个微信交流一下吗?我微信4510461,不是小白,请放心

**Comment by TKkk-iOSer** [comment]
fixed
