### ISSUE TITLE
点开消息内的图片----闪退

### ISSUE THREAD

**Issue by iszhuzhi** [TKkk-iOSer/WeChatPlugin-MacOS#189]
大神，为何我使用微信，点别人发的图片和自己发的图片，都是闪退？

mac os 10.11.6   
微信版本 2.3.10

追随小助手更新了4个版本，也卸载过，均出现闪退，难道是Mac的 os系统缘故？还是微信版本的缘故呢？

**Comment by chenony** [comment]
你试一下 不安装小助手 还闪退么。还闪退就是mac的问题。

**Comment by TKkk-iOSer** [comment]
@iszhuzhi 10.11.6 的话有可能是调用了一些 10.13 方法的 api 导致的…可以 试下 @chenony 所说的方法。

**Comment by iszhuzhi** [comment]
@TKkk-iOSer @chenony 刚刚试了一下，完全删文件夹卸载小助手，重新打开微信的图片，果然是闪退


哈哈，感谢两大神！！原来之前卸载小助手是没卸载彻底……所以！！
