### ISSUE TITLE
请问怎么生成链接，然后发送出去

### ISSUE THREAD

**Issue by gohitbear** [TKkk-iOSer/WeChatPlugin-MacOS#19]
带有标题、内容、URL、图标的邀请链接

**Comment by TKkk-iOSer** [comment]
生成链接？能描述的详细点么，不太懂…

**Comment by gohitbear** [comment]
比如我的好友发送了一篇文章给我，我点击右键，有一个转发选项，这在web端是没有的。
我的需求是：
好友发送如下json给我
{"titile":"aaa","content":"aaa","url":"aaa","logo":"aaa"}
我能解析数据并且发送成链接给指定群/好友

**Comment by TKkk-iOSer** [comment]
感觉好像不是很实用，最近也比较忙，以后有时间试下
