### ISSUE TITLE
是否可以实现通过快捷键或者Alfred快捷显示新消息的功能

### ISSUE THREAD

**Issue by shangvven** [TKkk-iOSer/WeChatPlugin-MacOS#195]

**Comment by TKkk-iOSer** [comment]
这个直接在通知中心查看不就好了么

**Comment by shangvven** [comment]
可能和个人习惯不同吧，我很少用到通知中心，消息的预览会关闭，所以消息过来只看到提示，接下来的操作想通过像QQ一样快捷打开到发送者的消息界面，而不是每次打开微信，早点到对应的发送者界面。
不知道是否这样习惯的朋友多不，QQ有这样操作，不太明白微信为什么没这个功能。
