### ISSUE TITLE
开启防撤回消息，使用一段时间发现点击小视频，每次都卡主，无法播放

### ISSUE THREAD

**Issue by loriswang** [TKkk-iOSer/WeChatPlugin-MacOS#199]

**Comment by loriswang** [comment]
不知道 有没有人遇到这样的状况

**Comment by TKkk-iOSer** [comment]
我倒是没遇到过，系统跟微信版本呢？关了防撤回就不会了么？

**Comment by TKkk-iOSer** [comment]
无法复现

**Comment by feepees** [comment]
对的，好像内存有问题




| |
feepees
邮箱：feepees_lee@163.com
|

签名由 网易邮箱大师 定制

在2018年04月08日 22:10，TK 写道：

Closed #199.
