### ISSUE TITLE
能不能直接提供 dmg 包,哈哈

### ISSUE THREAD

**Issue by xhp281** [TKkk-iOSer/WeChatPlugin-MacOS#2]

**Comment by TKkk-iOSer** [comment]
之后试试

**Comment by TKkk-iOSer** [comment]
现在完善了shell脚本，我觉得不用dmg包了哈哈。直接在 Terminal 中执行 `./Other/Install.sh` 就行了。

**Comment by xhp281** [comment]
帅




发自网易邮箱大师
在2017年08月18日 17:41，TK 写道：

现在完善了shell脚本，我觉得不用dmg包了哈哈。直接在 Terminal 中执行 ./Other/Install.sh 就行了。
