### ISSUE TITLE
最新版本不能正常运行

### ISSUE THREAD

**Issue by Devtll** [TKkk-iOSer/WeChatPlugin-MacOS#20]
![8085e7c2-2a04-495a-9f7a-23d890645035](https://user-images.githubusercontent.com/3726107/29595701-c1939cac-87eb-11e7-9a96-416fdc950da7.png)
把edit.png删了后能build成功，但是不能run

**Comment by TKkk-iOSer** [comment]
已修复，在pull试试。

**Comment by Devtll** [comment]
build成功，还是不能run呢？ Run还是灰色的

**Comment by TKkk-iOSer** [comment]
有没有先clear一下？

**Comment by Devtll** [comment]
![record](https://user-images.githubusercontent.com/3726107/29596644-a44e6ba4-87f0-11e7-9264-17980c2bbf77.gif)
有clear，Run按钮是灰色的，为什么

**Comment by TKkk-iOSer** [comment]
clear 不行的话可以重新 clone 再试试，我看图中的项目的图标有点不一样.
![QQ20170823-104726@2x.png](http://upload-images.jianshu.io/upload_images/965383-65a2c8eb04e06d06.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)，

你看下`Edit Scheme` 中的Executable 有没有选中WeChat.app
![Edit Scheme.png](http://upload-images.jianshu.io/upload_images/965383-26dbb068acb8998f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240).

如果选中的话还是不行，那么就用shell安装，`./Other/Install.sh`.

**Comment by TKkk-iOSer** [comment]
或者把Xcode WeChat 全退了试试，有时候是Xcode 大姨妈了

**Comment by Devtll** [comment]
![0f23e17a-fa7f-4186-a11e-9d74a1176ac0](https://user-images.githubusercontent.com/3726107/29596914-09180c56-87f2-11e7-9425-442e0801ce83.png)
确实没有一个app，为毛会这样呢。。我重新clone一下吧

**Comment by TKkk-iOSer** [comment]
可能真的是 Xcode 大姨妈了，哈哈哈

**Comment by TKkk-iOSer** [comment]
现在可以了么

**Comment by Devtll** [comment]
可以了，我手动选的WeChat.app。。。
