### ISSUE TITLE
最新2.3.11版本失效

### ISSUE THREAD

**Issue by i0ntempest** [TKkk-iOSer/WeChatPlugin-MacOS#200]
RT，登陆不能，无限弹出扫码窗口

**Comment by TKkk-iOSer** [comment]
ok，有时间再是陪下

**Comment by TKkk-iOSer** [comment]
请求问2.3.11还有其他问题么

**Comment by TKkk-iOSer** [comment]
先取消免认证 跟 快速登录 再试试😂

**Comment by i0ntempest** [comment]
卧槽 莫名其妙的好了 明明昨天无限弹二维码无法登陆 结果刚才进去了 免认证也正常 迷？？？

**Comment by i0ntempest** [comment]
我猜是不是跟扫码的过程有冲突 因为短期重新登录不需要扫码 这样直接从手机确认是可以登录的

**Comment by hickeybin** [comment]
最新2.3.11版本失效  我也试了安装了没效果

**Comment by TKkk-iOSer** [comment]
现在还有哪些功能失效了？ @i0ntempest @hickeybin

**Comment by i0ntempest** [comment]
目前没有发现
