### ISSUE TITLE
懒人版本安装后  如何更新.....

### ISSUE THREAD

**Issue by ChokW** [TKkk-iOSer/WeChatPlugin-MacOS#201]

**Comment by TrevoryZhou** [comment]
是啊，不能更新，要把原来下载的先删掉么？

**Comment by TKkk-iOSer** [comment]
用这个吧 `cd ~/Downloads && rm -rf WeChatPlugin-MacOS && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git --depth=1 && ./WeChatPlugin-MacOS/Other/Install.sh`

**Comment by ChokW** [comment]
可以用 多谢 @TKkk-iOSer
