### ISSUE TITLE
安卓手机和Mac客户端无法兼容，iPhone+Mac则没问题

### ISSUE THREAD

**Issue by kobe1941** [TKkk-iOSer/WeChatPlugin-MacOS#202]
如题，一个账号在安卓手机上登录，然后扫码登录Mac客户端后，Mac客户端的添加好友功能失效，每次添加好友时，微信会弹窗提示版本过低，请升级版本。但是版本已经是最新了。

同样的操作，iPhone和Mac搭配则没有问题。
安卓和Windows搭配也没有问题。
iPhone和Windows客户端搭配也没有问题。

好神奇？？？

**Comment by kobe1941** [comment]
好像也不是每台安卓手机+Mac客户端都会有这个问题，只是出现问题的例子是安卓+Mac而已

**Comment by kobe1941** [comment]
![image](https://user-images.githubusercontent.com/7099017/37817925-728ad200-2eb3-11e8-9371-ebd89cccccdf.png)

**Comment by Jiangvoid** [comment]
我用的就是安卓，但是没有出现你的问题。

**Comment by TKkk-iOSer** [comment]
是否是跟你的安卓微信版本、mac微信版本有关？

**Comment by kobe1941** [comment]
还不明确具体原因。。
