### ISSUE TITLE
Alfred搜索功能两个微信情况下有问题

### ISSUE THREAD

**Issue by haoxuexiaoyao** [TKkk-iOSer/WeChatPlugin-MacOS#203]
多开了一个微信,Alfred搜索只能搜索第一个微信里面的联系人进行聊天,请问这个同时登录两个微信的话是无法搜索第二个登录的微信联系人是么

**Comment by TKkk-iOSer** [comment]
是的，无法搜索到 https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/2
