### ISSUE TITLE
什么时候加入朋友圈啊

### ISSUE THREAD

**Issue by kissnger** [TKkk-iOSer/WeChatPlugin-MacOS#204]
能加入朋友圈浏览么？

**Comment by TKkk-iOSer** [comment]
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/183  https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/57 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/175
