### ISSUE TITLE
希望给自动回复增加判断条件

### ISSUE THREAD

**Issue by chengsixgoold** [TKkk-iOSer/WeChatPlugin-MacOS#207]
你好，我使用这个插件已经一个多月了，我这里有一个需求，我来详细说一下：
由于我平常会和很多人在微信上进行交流，所以我会设置自动回复，但是当一个人给我发消息我没有回复时，就会一直自动回复。我想的是，自动回复是否只出发一次。第一出发自动回复后，我没有回复，这个联系人再给我发消息就不会出发自动回复了。希望插件能加一个这样的判断条件，当然也可以作为插件的一个选择项出现。

**Comment by TKkk-iOSer** [comment]
可以增加个选择项，只是现在自动回复要加的选择项有点多，延迟回复、过滤的好友、群聊选择等。之后在想下展示的细节。你这么一说感觉可以在远程控制里面增加个小助手功能的开关了。

**Comment by chengsixgoold** [comment]
好的，感谢作者。
