### ISSUE TITLE
请问下微信更新后, 必须得重新安装插件吗 ? 谢谢

### ISSUE THREAD

**Issue by bigtreenono** [TKkk-iOSer/WeChatPlugin-MacOS#211]
因为微信更新的频率也蛮快的, 导致每次更新后都得重新安装一遍插件, 也是有点麻烦..

不知道是不是我使用姿势不对, 谢谢

**Comment by TKkk-iOSer** [comment]
是的，重新安装，之后看能不能通过 homebrew 安装

**Comment by olafchou** [comment]
<img width="702" alt="snipaste_2019-01-25_09-47-34" src="https://user-images.githubusercontent.com/19890798/51719944-698c0000-2086-11e9-8e33-209aad32dcb5.png">

怎么安装，不会啊？？？？
