### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ddddyyy** [TKkk-iOSer/WeChatPlugin-MacOS#216]
diff: /Podfile.lock: No such file or directory

**Comment by happybobo** [comment]
Podfile.lock是pod install之后生成的锁定Podfile的三方库版本的文件，可以没有，运行pod install后就有了

**Comment by ddddyyy** [comment]
@happybobo 运行pod install之后也没有

**Comment by TKkk-iOSer** [comment]
请先去安装Cocoapods
