### ISSUE TITLE
希望增加删除聊天记录功能

### ISSUE THREAD

**Issue by TomatoFryEggs** [TKkk-iOSer/WeChatPlugin-MacOS#22]

**Comment by TKkk-iOSer** [comment]
删除聊天记录？自带的不是有这功能了么

**Comment by TomatoFryEggs** [comment]
有删除最近联系人的操作么？不是得一个个的删除？
TK <notifications@github.com<mailto:notifications@github.com>>于2017年9月1日 周五11:42写道：

删除聊天记录？自带的不是有这功能了么

**Comment by TKkk-iOSer** [comment]
这个感觉没什么必要吧😂 QQ也是没有选中多个然后删除的操作，平时也没有需求

**Comment by TomatoFryEggs** [comment]
有的，哈哈哈
TK <notifications@github.com<mailto:notifications@github.com>>于2017年9月5日 周二21:02写道：

Closed #22<https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/22>.

**Comment by TKkk-iOSer** [comment]
加了，多选删除最近联系人

**Comment by TomatoFryEggs** [comment]
感谢🙏
