### ISSUE TITLE
这个是盗版你的吗？

### ISSUE THREAD

**Issue by qq645381995** [TKkk-iOSer/WeChatPlugin-MacOS#221]
https://github.com/Natoto/WeChatPlugin
看他的 gif 图 跟你的一样 
不过 TK 命令应该是你的名字的简称吧，应该这个本身是你先做的
但是他有个查看朋友圈 这个功能不错

**Comment by TKkk-iOSer** [comment]
是的，朋友圈的话原本也不是他做的吧，他是第一个fork的，是 [AlayshChen](https://github.com/AlayshChen) 这个大佬做的(~~插件的制作也是看他的文章的，只是后来他删除了~~)，然后原作者删除了，就成了他的了，看下git commit 记录就知道了。

**Comment by Jackielzq** [comment]
我刚也看到了那个。。。看截图和你的都一样。。。

**Comment by qq645381995** [comment]
我只希望什么时候能添加上朋友圈功能
