### ISSUE TITLE
语音远程控制mac无法使用

### ISSUE THREAD

**Issue by maxzsc** [TKkk-iOSer/WeChatPlugin-MacOS#226]
![image](https://user-images.githubusercontent.com/3434888/38595275-72a7c00c-3d10-11e8-81e8-3a4e82a32504.png)
如图，第一条消息是文字发出，可以成功执行。
第二条消息是语音发出，无法成功执行。

**Comment by TKkk-iOSer** [comment]
你需要用语音说出 ScreenSave 才可以…请仔细查看demo演示
