### ISSUE TITLE
无法开启自动回复功能

### ISSUE THREAD

**Issue by Deeer** [TKkk-iOSer/WeChatPlugin-MacOS#23]
点击自动回复，弹出自动回复窗口，已经设置自动回复列表，并勾选。
但是还是没法开启，发送后，没有办法自动回复

**Comment by TKkk-iOSer** [comment]
1. 请问下能否截下图？
2. 请问下是否是在群聊里面发送的消息？群聊自动回复自否有勾选？

**Comment by Deeer** [comment]
![image](https://user-images.githubusercontent.com/8898286/30090050-6ce6c686-92e3-11e7-8cd4-11c016fb88cb.png)
1.点击微信小助手-开启自动回复，回弹出自动回复设置窗口，但是包括回复列表和群聊开启自动回复都是已经勾选的。
2.在窗口上方的弹出菜单栏中一直无法显示勾选状态。每次点击都是进行上面的步骤。
3.单聊群聊都试过，都是没有用
4.微信版本：Version. 2.2.5 (8370)
   MacOS版本： macOS Sierra 10.12.6

**Comment by TKkk-iOSer** [comment]
@Deeer 我这边的没问题，微信版本是2.3.0；有可能是微信版本太低，之前是从2.2.8开始做的，尝试更新下微信试试。

**Comment by riusksk** [comment]
我升级到微信2.3.2之后，也是同样无法开启自动回复了

**Comment by TKkk-iOSer** [comment]
`在`后面是否存在空格？有尝试删除该回复再新增一个自动回复试试么？

**Comment by riusksk** [comment]
没有空格

**Comment by TKkk-iOSer** [comment]
好神奇…我之前都没遇到过…尝试删除掉所有的自动回复，再新增一条，然后重新勾选左边的选中框试试。

**Comment by riusksk** [comment]
还是不行

**Comment by Deeer** [comment]
升级之后应该就会遇到了 @TKkk-iOSer

**Comment by TKkk-iOSer** [comment]
我的是微信 Version. 2.3.0 (9359) ，mac 10.12.4 (16E195)，该不会真的这么坑吧…10.12.6的不行… 话说很奇怪，为什么开始创建的时候，选中框是默认开启的，我设置的是默认不开启

**Comment by TKkk-iOSer** [comment]
话说你们之前有装过这个插件么？

**Comment by Milktry** [comment]
![snip20170907_5](https://user-images.githubusercontent.com/6133741/30146504-03130f56-93cb-11e7-99cc-54d0dcd77450.png)
![snip20170907_6](https://user-images.githubusercontent.com/6133741/30146505-038207ee-93cb-11e7-953d-98b37b4112d5.png)
你好，我是最新版系统，osx：10.12.5   无法开启自动回复，希望能改善它们，取消开启微信验证~

**Comment by Deeer** [comment]
没有哦，你这个是第一个哦，我还从原来的版本升级到了2.3.2。
依旧不行
现在想找个2.3.0的安装包试试，或者你有吗，发我个看看，是不是版本的问题
@TKkk-iOSer

**Comment by TKkk-iOSer** [comment]
@Deeer 刚刚更新了下2.3.2的，是可以自动回复的。看来有可能是os系统问题了，我的是10.12.4的，你们的是10.12.5和10.12.6的。

**Comment by TKkk-iOSer** [comment]
@Deeer @Milktry 请问下其他功能能够使用么？ 有没有尝试卸载该插件，重新再安装一次？

**Comment by Deeer** [comment]
撤回功能OK，其他功能暂未尝试。
我卸载后，重新安装依旧不能使用
@TKkk-iOSer

**Comment by sfdye** [comment]
+1
我也是不能自动回复，打不了钩，防止撤回可以用。
10.13 Beta WeChat最新版

**Comment by Milktry** [comment]
@sfdye @Deeer  我和你们一样  无法勾选选项

**Comment by sfdye** [comment]
昨天突然可以用了 重开几次微信试试

**Comment by TKkk-iOSer** [comment]
@Milktry 菜单栏的选中被我给取消了，所以不会选中的，因为之前是单回复所以有勾选，现在是多回复，各个回复有各自的选框。 

@sfdye 这么神奇…
