### ISSUE TITLE
[bug]［UE］自动回复两个号设置的话会循环

### ISSUE THREAD

**Issue by xuanll** [TKkk-iOSer/WeChatPlugin-MacOS#231]
这样用户体验不太好
  @TKkk-iOSer 有空改进

附图如下

<img width="620" alt="bug" src="https://user-images.githubusercontent.com/6114377/38661784-94d88a12-3e64-11e8-8c0d-a67cb4d9d3ea.png">

**Comment by TKkk-iOSer** [comment]
1. 这种概率的话仅在双方都装了插件且同时设置了相匹配的关键字与回复中，概率比较小。
2. 大概率就是自己跟自己小号了。
3. 可以人为的去杜绝。
4. 容我想想
