### ISSUE TITLE
clone下来，pods.xcodeproj错误。

### ISSUE THREAD

**Issue by WTFCSL** [TKkk-iOSer/WeChatPlugin-MacOS#232]
工程不管down下来，还是Git拉下来。点凯WeChatPlugin.xcworkspace后，pods.xcodeproj 都是红色。找不到。工程内Pods文件里的Headers、Local Podspecs、Target Support Files、文件都是空的。

**Comment by TKkk-iOSer** [comment]
CocoaPods 了解一下
