### ISSUE TITLE
远程控制失效

### ISSUE THREAD

**Issue by zhaowweny** [TKkk-iOSer/WeChatPlugin-MacOS#234]
远程控制功能开启后过一会会失效，目前看好像只是网易云音乐会失效，系统控制还有效。

**Comment by TKkk-iOSer** [comment]
有时候是会这样，`系统偏好设置 ==> 安全性与隐私 ==> 隐私 ==> 辅助功能` 中会关闭，不过出现的概率很小，目前也没找到复现路径。

**Comment by albertofwb** [comment]
我也发现了，有时候控制网易云音乐会失效

**Comment by zhaowweny** [comment]
@TKkk-iOSer 嗯，我这开启了，系统远程控制没问题，就网易云音乐有时候会失效，可能有其他原因吧。

**Comment by TKkk-iOSer** [comment]
重新更改了远程控制的回调提示，如果失败了会有回调消息。例如：`execution error: “System Events”遇到一个错误：“osascript”不允许辅助访问。 (-1719)`则是辅助功能未开启

**Comment by CCBrother** [comment]
<img width="539" alt="wechat10aa4c178e153ebdac5be7da5e631202" src="https://user-images.githubusercontent.com/14049399/48539669-d8184900-e8f2-11e8-9347-0975bf2fc2ac.png">
辅助功能已经开启了，还是出现这个错误
