### ISSUE TITLE
command + Q 退出微信后，再次打开微信时，需要在手机上确认或者重新扫码才能登陆

### ISSUE THREAD

**Issue by albertofwb** [TKkk-iOSer/WeChatPlugin-MacOS#238]
微信版本：2.3.11
OS 版本：10.13.4

相关日志：
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFHTTPSessionManager is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a008) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d97e8). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFNetworkReachabilityManager is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x108049f68) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9888). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFSecurityPolicy is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x108049fb8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d98d8). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFQueryStringPair is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a148) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9928). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFHTTPRequestSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a198) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9978). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFStreamingMultipartFormData is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a1c0) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d99a0). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFMultipartBodyStream is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a210) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d99f0). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFHTTPBodyPart is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a238) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9a18). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFJSONRequestSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a2d8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9ab8). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFPropertyListRequestSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a328) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9b08). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFHTTPResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a378) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9b58). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFJSONResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a3c8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9ba8). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFXMLParserResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a418) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9bf8). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFXMLDocumentResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a468) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9c48). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFPropertyListResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a4b8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9c98). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFImageResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a508) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9ce8). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFCompoundResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a558) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9d38). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFURLSessionManagerTaskDelegate is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a058) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9d88). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class _AFURLSessionTaskSwizzling is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a0d0) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9e00). One of the two will be used. Which one is undefined.
Apr 15 16:04:57 Albert WeChat[73792]: objc[73792]: Class AFURLSessionManager is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x10804a0f8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x1077d9e28). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFHTTPSessionManager is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b008) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb47e8). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFNetworkReachabilityManager is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152af68) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4888). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFSecurityPolicy is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152afb8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb48d8). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFQueryStringPair is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b148) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4928). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFHTTPRequestSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b198) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4978). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFStreamingMultipartFormData is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b1c0) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb49a0). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFMultipartBodyStream is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b210) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb49f0). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFHTTPBodyPart is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b238) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4a18). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFJSONRequestSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b2d8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4ab8). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFPropertyListRequestSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b328) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4b08). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFHTTPResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b378) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4b58). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFJSONResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b3c8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4ba8). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFXMLParserResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b418) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4bf8). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFXMLDocumentResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b468) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4c48). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFPropertyListResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b4b8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4c98). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFImageResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b508) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4ce8). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFCompoundResponseSerializer is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b558) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4d38). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFURLSessionManagerTaskDelegate is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b058) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4d88). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class _AFURLSessionTaskSwizzling is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b0d0) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4e00). One of the two will be used. Which one is undefined.
Apr 15 16:24:14 Albert WeChat[74846]: objc[74846]: Class AFURLSessionManager is implemented in both /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking (0x11152b0f8) and /Applications/WeChat.app/Contents/MacOS/WeChat (0x110cb4e28). One of the two will be used. Which one is undefined.

**Comment by TKkk-iOSer** [comment]
是否有勾选免认证登录？

**Comment by albertofwb** [comment]
当然有勾选啊
我发现退出微信之后如果在短时间内重新打开，微信就会自动登录
如果隔得时间比较久（超过一个小时？？？）就需要重新再手机上确认了
不知道有没有其他人遇到过这个问题？

**Comment by TKkk-iOSer** [comment]
哦，这个我倒没有去试过，我一般都是长期都挂着微信

**Comment by BenjaminGao** [comment]
我也有次问题

**Comment by yangnaihua** [comment]
我也有问题

**Comment by TKkk-iOSer** [comment]
重新安装最新的小助手试试，有些逻辑调整了
