### ISSUE TITLE
是否可能实现多窗口聊天？

### ISSUE THREAD

**Issue by leverglowh** [TKkk-iOSer/WeChatPlugin-MacOS#239]
研究了很久，好像目前并没有将某个聊天窗口单独提出从而达到同时显示两个聊天窗口的方式。
想知道这个功能是否可能实现，还是需要官方自己良心发现开发哈哈

**Comment by TKkk-iOSer** [comment]
感觉还是官方良心发现吧，个人业余做的没办法做到像官方那么完美。
