### ISSUE TITLE
自动回复加入多个回复内容，可以每次随机回复其中一个

### ISSUE THREAD

**Issue by huanlingex** [TKkk-iOSer/WeChatPlugin-MacOS#246]
可以对同一句话回复两个不同的答案。例如
设置自动回复内容为：在吗？
回复内容1:在
回复内容2：在的

第一次A发：在吗
回复：在

第二次A发：在吗
回复：在的

如果预设内容有N个，那么每次回复的内容为N中的随机子集

**Comment by TKkk-iOSer** [comment]
当前版本已支持，请详细查看readme
