### ISSUE TITLE
希望也能增加看朋友圈的功能

### ISSUE THREAD

**Issue by lbaggiocn** [TKkk-iOSer/WeChatPlugin-MacOS#249]
希望也能增加看朋友圈的功能

**Comment by TKkk-iOSer** [comment]
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/183  https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/57 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/175
