### ISSUE TITLE
weChat version 2.3.12 does not working

### ISSUE THREAD

**Issue by Privilger** [TKkk-iOSer/WeChatPlugin-MacOS#251]
I just update my weChat. And it seems can not working in the new weChat.

**Comment by yangnan221** [comment]
自动登录失效，防撤回能用，其他功能还没测试

**Comment by Cat7373** [comment]
+1，免认证登录失效后登录体验很诡异

打开微信，手机弹出登录确认，然而点了确认毫无卵用，再扫码微信提示点确认登陆，手机上点确认还是毫无卵用😂

**Comment by Privilger** [comment]
waiting for update 😂

**Comment by TKkk-iOSer** [comment]
你们更新微信这么勤的，我都快跟不上了😂。(目前还在开发一个版本，还在优化，之后也适配下2.3.12

**Comment by RyanCN** [comment]
2.3.12确实无法自动登录了 不是更新快 是开了自动更新很郁闷……

**Comment by jiabanxian** [comment]
2.3.12我这边是直接失效了呢，顶栏根本看不到微信小助手的选项

**Comment by lishuzhi1121** [comment]
Mac版微信 2.3.12 估计做了什么改动，很欣赏楼主，给楼主发个下午茶，等下读一波源码，学习一下，还请大佬赐教～😂

**Comment by Cat7373** [comment]
@RyanCN 自己手动更的路过😂

**Comment by yangnan221** [comment]
@miniers 请问如何退回老版本？

**Comment by yangnaihua** [comment]
有问题的路过

**Comment by lishuzhi1121** [comment]
@yangnan221 最快的就是删掉自己的微信，从朋友那边拷贝一个低版本的就行了

**Comment by RyanCN** [comment]
@Cat7373 我就不该开自动更新……我表示很无奈………………

**Comment by TKkk-iOSer** [comment]
Fixed
