### ISSUE TITLE
自动回复语音消息

### ISSUE THREAD

**Issue by Baogaitou** [TKkk-iOSer/WeChatPlugin-MacOS#255]
是否可以支持将 MP3音乐文件作为语音消息回复给好友? 
看到 MessageService.h 里面有相应的方法，不知道是否支持 MP3格式，微信语音应该都是 speex 格式的，两种格式互转倒是应该没有问题。

BTW: 感谢 TKkk 及各位 committer 的付出.

**Comment by TKkk-iOSer** [comment]
我觉得没这个必要吧，能用文字回复就可以了，语音的话每次都回复同一个调同一句话就会觉得怪怪的。
