### ISSUE TITLE
请教一下 怎么通过消息的msgID获取原图

### ISSUE THREAD

**Issue by YangSugar** [TKkk-iOSer/WeChatPlugin-MacOS#259]
怎么获取 微信聊天中点击后的大图呢？ 感谢

**Comment by TKkk-iOSer** [comment]
没去试过…

**Comment by loufq** [comment]
同问，缩略图会自动下载，但是大图只有打开聊天窗口的时候才会自动下载。
【尝试使用CdnComHelper StartDownloadImage 方法并无效果】
