### ISSUE TITLE
还是需要验证密码的，提醒下大家

### ISSUE THREAD

**Issue by catroom** [TKkk-iOSer/WeChatPlugin-MacOS#26]
<img width="565" alt="default" src="https://user-images.githubusercontent.com/17866068/30047958-667bfb7e-9246-11e7-8801-fa36394fc458.png">
然后不会立刻出现，还是重启登录微信才显示

**Comment by TKkk-iOSer** [comment]
输入密码是为了修改微信的所有权，使插件能够写入。若怕有后门，可以自行查看代码。

**Comment by catroom** [comment]
thanks
