### ISSUE TITLE
登陆的时候会卡住一会，然后才会弹出扫码登陆的。

### ISSUE THREAD

**Issue by xbdsky** [TKkk-iOSer/WeChatPlugin-MacOS#261]
微信版本 Version. 2.3.13 (10763) 
![](https://ws1.sinaimg.cn/large/62c5393fgy1fqz2yolkb8j20ds0d60yp.jpg)
大概会卡个1~3分钟的样子，然后弹出这个
![](https://ws1.sinaimg.cn/large/62c5393fgy1fqz2zsi0xfj208z07nt97.jpg)

**Comment by TKkk-iOSer** [comment]
已更新，重新安装试试

**Comment by xbdsky** [comment]
好的
