### ISSUE TITLE
为什么只支持 网易云音乐 不支持 QQ 音乐呢？

### ISSUE THREAD

**Issue by Tespera** [TKkk-iOSer/WeChatPlugin-MacOS#266]
为什么只支持 网易云音乐 不支持 QQ 音乐呢？添加一下 QQ 音乐的支持呗！谢谢！

**Comment by Tespera** [comment]
我知道大家用网易云音乐是因为一种情怀，也都是很有诗意的人，我也一直在用，但是网易歌太少了，有时候免不了就要用 QQ 音乐，而且 QQ 音乐有河蟹版，可以免费下载所有高品质歌曲，所以 QQ 音乐也还是很常用的，希望能够考虑添加一下 QQ 音乐的支持。万分感谢！也希望网易云音乐尽快走出困境。[手动送花花]

**Comment by 1290259791** [comment]
请问你辅助功能里面添加了几个，我的无法控制
execution error: “System Events”遇到一个错误：不能获得“process "NeteaseMusic"”。 (-1728)

**Comment by 1290259791** [comment]
execution error: “System Events”遇到一个错误：不能获得“menu bar 1 of process "NeteaseMusic"”。无效的索引。 (-1719)

**Comment by acbetter** [comment]
@1290259791 #302

**Comment by TKkk-iOSer** [comment]
@Tespera 按照 @acbetter 说的做就行了
