### ISSUE TITLE
无法开启自动回复

### ISSUE THREAD

**Issue by caesar-cheng** [TKkk-iOSer/WeChatPlugin-MacOS#27]
点击微信小助手-开启自动回复
直接异常退出

**Comment by violetcherry** [comment]
我也存在同样的问题，防止撤回功能正常。但按下 command + k 开启自动回复，微信就自动异常退出，远程控制功能也是同样的异常退出。

[按照这个链接提示的](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/21) 

“远程控制的是不是没问题？
应该是 mac 的版本太低了。有些api只有10.12才能用。 你试着把TKAutoReplyWindowController.m文件中的102行的[alert setAlertStyle:NSAlertStyleWarning];这句代码注释掉 。重新 build + run 试试。” 
build 失败，报错原因看不明白。

微信版本： Version. 2.3.2 (9414)
系统: Darwin violetcherry.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by TKkk-iOSer** [comment]
是否mac版本在10.12以下？

现已更新代码，再试试。

**Comment by violetcherry** [comment]
我的 macOS 是10.11版本， 未升级至10.12版本。

**Comment by TKkk-iOSer** [comment]
重新下载代码，再试试看自动回复的会不会异常退出。

**Comment by violetcherry** [comment]
@TKkk-iOSer 重新试过了，把整个代码都删除了，并重新用./Install.sh进行了安装，自动回复功能开启就会导致微信异常退出。

**Comment by TKkk-iOSer** [comment]
能否发下报错信息？全部的也行，不然我这边也不好排错

**Comment by violetcherry** [comment]
您好！报错信息我贴在这里，请您抽空看看 https://paste.ubuntu.com/25479438/

**Comment by TKkk-iOSer** [comment]
奇怪，之前问了一个10.12.6的，他的不会出现这样的问题。

@violetcherry  @caesar-cheng 能否打开`实用工具-控制台`(如下图)，然后在输入框中输入`wechat`,在点击微信崩溃前先清除一下，然后崩溃了把当前的所有log拷贝出来看下？

![WX20170910-011908@2x.png](http://upload-images.jianshu.io/upload_images/965383-1b76fdfe5af5f21f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
