### ISSUE TITLE
菜单栏不可用了。。

### ISSUE THREAD

**Issue by nomistar** [TKkk-iOSer/WeChatPlugin-MacOS#271]
今早提示更新，我就更新了，然后更新完自动登录、拦截撤回可以用，但是菜单不可选了
<img width="188" alt="screen shot 2018-05-13 at 12 29 17" src="https://user-images.githubusercontent.com/39230816/39963851-8c16f528-56a9-11e8-88b3-d3c5498ffbf6.png">

**Comment by nomistar** [comment]
我退出后再打开 重启什么的都试过了  最后是app store更新了最后版本-卸载插件重装后解决的

**Comment by TKkk-iOSer** [comment]
是的，特地这么设计的，只有登录之后才能点击。原因是现在分账户设置了，就是不同的账号对应不同的自动回复设置与远程控制设置，所以没登录的时候无法查看。

**Comment by nomistar** [comment]
谢谢！辛苦了

**Comment by sunOpar** [comment]
+1
