### ISSUE TITLE
更新安装v1.7之后，工具栏第一次可配置，关闭微信后再次启动，就无法配置

### ISSUE THREAD

**Issue by Zjingwen** [TKkk-iOSer/WeChatPlugin-MacOS#273]
![image](https://user-images.githubusercontent.com/8531277/39970046-6c2f94ae-5717-11e8-8a25-33e56f8afbdb.png)

更新v1.7之后，工具栏可以配置，之后完全退出微信再登录后，工具栏就无法配置了。

我选择更新微信，无法解决。

我将微信助手卸载，再次安装。重新登录微信后，可以配置。但是当我关闭微信，再次打开，就无法配置。

自动登录的功能，自动回复的功能都是完好的。

我只有登录一个微信，并没有多个微信。

* weChat：2.3.13
* 微信工具助手：1.7
* macOS：10.12.6 (16G29)

**Comment by sunOpar** [comment]
+1

**Comment by chatwyn** [comment]
+1

**Comment by TKkk-iOSer** [comment]
都是10.12.6的么？我这边倒是不会。
如果是未登录不可点击是正常的，登录之后才能点击。https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/271

**Comment by chatwyn** [comment]
我是10.13.2

**Comment by chatwyn** [comment]
试了一下 如果是自动登录的 就不能用了 如果不是 可以用

**Comment by TKkk-iOSer** [comment]
@chatwyn 开启免认证登录就有可能出现是吧，大概知道原因了

**Comment by chatwyn** [comment]
![image](https://user-images.githubusercontent.com/12781400/40111435-684c3f3e-5935-11e8-9dfa-4c4c71093f5a.png)
  开启这个就不能用了

**Comment by TKkk-iOSer** [comment]
已更新

**Comment by Zjingwen** [comment]
已经OK了，谢谢
