### ISSUE TITLE
iOS端切换微信账号后 mac端自动退出

### ISSUE THREAD

**Issue by RyanCN** [TKkk-iOSer/WeChatPlugin-MacOS#276]
在iOS微信工具里切换第二个账号的时候，mac端本身已经登录的第一个账号被自动退出到二维码界面，且拦截撤销功能失效

**Comment by LunaLambda** [comment]
请问一下您Mac端的微信版本号是2.3.13吗？我在这个版本下不知道什么原因显示不出微信小助手……

**Comment by RyanCN** [comment]
微信版本是2.3.12（10717） 微信小助手正常 就是免认证不正常

**Comment by TKkk-iOSer** [comment]
正常操作，确实会这样。就好像你点击了iOS端的`退出mac微信`一样。

**Comment by wangxiexe** [comment]
有什么办法不退出吗？ 感觉 QQ这块就人性化多了

**Comment by luanwulin** [comment]
@TKkk-iOSer 同求这个功能，有时候几个微信，又没有几个手机，切换的时候电脑就退出了。能不能保证电脑不要退出
