### ISSUE TITLE
图片添加为表情包的功能？

### ISSUE THREAD

**Issue by sugarAndsugar** [TKkk-iOSer/WeChatPlugin-MacOS#278]
我用Mac版微信 最想要的是别人发表情包或图片 自己可以直接收藏到自己表情包里就好了，就像QQ右键 添加为漫游表情这样。

**Comment by QiQiBiBi** [comment]
聊天窗口表情包复制 & 存储 这个没找着，图上右键？没看到

**Comment by sugarAndsugar** [comment]
嗯，如果是表情包直接可以右键收藏，图片需要复制 & 存储

**Comment by QiQiBiBi** [comment]
我的好像右键表情上没反应

观剑不则声 <notifications@github.com> 于 2018年6月11日周一 11:03写道：
