### ISSUE TITLE
希望能够自定义 MMappedKV和.rqd的位置

### ISSUE THREAD

**Issue by SparkYuan** [TKkk-iOSer/WeChatPlugin-MacOS#28]

**Comment by acbetter** [comment]
+1  
至少不要放在`~/Documents/`啊

**Comment by TKkk-iOSer** [comment]
主要是所有权改了，所以沙盒的位置也改了，导致一些文件的位置也跟着改变。这也就是为什么聊天记录会消息的原因…目前正在找解决方法。

**Comment by TKkk-iOSer** [comment]
@acbetter @SparkYuan 聊天记录消失与Documents目录新增部分文件的问题已修复，另外`.rqd`好像不是这个插件导致的，看了下里面的文件有QQ，微云，QQ音乐等等。

**Comment by SparkYuan** [comment]
@TKkk-iOSer 重新执行Uninstall.sh之后再Install.sh，Documents下还是会有MMappedKV。并且我的.rqd文件下只有一个文件，文件名是com.Tencent.JietuFramework，产生的时间跟我登陆微信的时间一致。

**Comment by TKkk-iOSer** [comment]
@SparkYuan 没有更新framework，现已更新，再试试，另外.rqd我再看看是什么原因
