### ISSUE TITLE
更新之后聊天记录全没了。。。

### ISSUE THREAD

**Issue by ladychili** [TKkk-iOSer/WeChatPlugin-MacOS#284]
是bug还是本来就是这样？？为什么更新个插件会对本地聊天记录有影响？

**Comment by TKkk-iOSer** [comment]
请检查下`微信-偏好设置-退出时保留聊天记录`是否有勾选

**Comment by TKkk-iOSer** [comment]
更新之后是否有登录过另一个不常登录的微信号？

**Comment by ladychili** [comment]
啊是先登陆过一个别的账号。这样会导致原来的聊天记录消失吗？

**Comment by ladychili** [comment]
btw 会话气泡有一点点错位 
![image](https://user-images.githubusercontent.com/27876613/40269386-bbb29de8-5b75-11e8-8787-673ab761f4ff.png)

**Comment by TKkk-iOSer** [comment]
* 前天试了下，登录了一个没在电脑上登过(或者很久没登过)的账号，然后微信设置里面应该是没有勾选退出时保留聊天记录，就把另一个账号的也给清了…所以估计是这个问题，目前解决办法是先强制保留聊天记录先。
* 会话气泡偏移我试了下你发的数字我这边是没出现，不知道是不是因为你设置了英文环境的原因，可以先卸载插件看下是否还是会偏移，会的话那就是官方的问题了。

**Comment by ladychili** [comment]
谢谢耐心回复～
* 这个确实是因为之前没有勾选保留聊天记录，刚才已经勾上了。
* 刚刚尝试卸载插件，气泡位置恢复了，不过也不能确定是插件导致的，因为之前装着插件的时候也是时不时才会偏移。观察一阵再装回来，看看是不是官方的bug。

![image](https://user-images.githubusercontent.com/27876613/40282040-ce0b91e8-5c60-11e8-9de5-6ed5032d3750.png)

btw可以关掉这个issue了。
开发辛苦，请大佬喝奶茶了，继续加油。^ ^

**Comment by TKkk-iOSer** [comment]
ok，蟹蟹打赏👌
