### ISSUE TITLE
自动回复能不能支持模糊匹配？

### ISSUE THREAD

**Issue by loricheung** [TKkk-iOSer/WeChatPlugin-MacOS#29]

**Comment by TKkk-iOSer** [comment]
这个因为怕会误发消息(微信里面有公司群)，所以就没有模糊匹配了。

**Comment by catroom** [comment]
是啊，我觉得也是需要模糊回复吧。例如发一句话里面有晚安，我想回复晚安。假如她发过来晚安啦就无法识别了有点尴尬啊。可以不可以这样匹配“晚安**” 晚安后面接什么都可以自动回复。

**Comment by TKkk-iOSer** [comment]
@catroom  照这个感觉最后是要加个正则匹配了… 有时间我再搞上

**Comment by TKkk-iOSer** [comment]
@loricheung @catroom 已添加正则
