### ISSUE TITLE
一直提示我更新

### ISSUE THREAD

**Issue by zhenhappy** [TKkk-iOSer/WeChatPlugin-MacOS#290]
一直提示我更新, 但是我点更新了, 然后到最后安装并重启应用点了一点反应都没有, 没办法成功更新
对了, 我的微信不是在默认的/Applications
不知道是不是跟这个有关系

**Comment by zhenhappy** [comment]
果然是这个问题, 有没有办法支持自定义微信的路径

**Comment by TKkk-iOSer** [comment]
可以修改Shell文件，另外更新的那个弹窗勾选不再提醒
