### ISSUE TITLE
手贱更新之后重新安装也没反应了

### ISSUE THREAD

**Issue by MYDEARBOMB** [TKkk-iOSer/WeChatPlugin-MacOS#293]
一直提示我更新 昨晚更新之后重新打开微信 没有小助手的显示了 重新安装之后再启动也不行

**Comment by TKkk-iOSer** [comment]
* 先查看下是否有重命名微信，或者更改微信的路径。如果有的话，那么更新安装都无效。
* 提示更新的是哪个版本的小助手？是要跳转到github的么？如果一直提示更新的话，那么可以勾选那个不再提醒。
* 没显示的话先卸载在安装试试。如果卸载不行的话，先到 `/Applications/WeChat.app/Contents/MacOS`路径下，删除 `WeChat_`和`WeChatPlugin.framework` ,把`WeChat_backup`改为 `WeChat`.这样就卸载成功了，然后重新安装。

**Comment by MYDEARBOMB** [comment]
卸载后重装 已经完美解决了 谢谢您
