### ISSUE TITLE
通过两种方法安装小助手，重启微信客户端后，仍未看到小助手？

### ISSUE THREAD

**Issue by brian32** [TKkk-iOSer/WeChatPlugin-MacOS#296]
按照提供的两种方式（懒人方法和普通方法）安装小助手，都提示成功。但重启微信仍未看到小助手出现。

**Comment by TKkk-iOSer** [comment]
更新安装方式，请重新试试。另外请检查微信是否再应用程序的文件夹中，以及是否更改微信.app名称

**Comment by brian32** [comment]
重新安装了一次，可以了，谢谢
