### ISSUE TITLE
懒癌姿势安装失败，但依旧提示成功

### ISSUE THREAD

**Issue by Liar1995** [TKkk-iOSer/WeChatPlugin-MacOS#304]
<img width="570" alt="wx20180611-130726 2x" src="https://user-images.githubusercontent.com/13048201/41218360-64cd241a-6d8d-11e8-9ca5-bb19b576cee1.png">

**Comment by SuperChenSSS** [comment]
你要再使用omw安装微信，自己看文档

**Comment by TKkk-iOSer** [comment]
可以去 [oh-my-wechat](https://github.com/lmk123/oh-my-wechat#oh-my-wechat) 反馈下

**Comment by lmk123** [comment]
这是由于权限问题导致的，见 lmk123/oh-my-wechat#3

另外我更新了项目，现在安装出错后会给出正确的提示：“下载失败，请稍后重试”，你可以重新安装 omw 试试。
