### ISSUE TITLE
2.3.14版本安装不上, 提示chmod: /usr/local/bin/omw: No such file or directory

### ISSUE THREAD

**Issue by 755966092** [TKkk-iOSer/WeChatPlugin-MacOS#305]
![image](https://user-images.githubusercontent.com/22684309/41265202-a50b0fc4-6e23-11e8-971f-6a287760ccde.png)

**Comment by TKkk-iOSer** [comment]
可以去 [oh-my-wechat](https://github.com/lmk123/oh-my-wechat#oh-my-wechat) 反馈下

**Comment by lmk123** [comment]
这是由于权限问题导致的，见 lmk123/oh-my-wechat#3
