### ISSUE TITLE
关闭撤回后无法撤回信息

### ISSUE THREAD

**Issue by Tasfa** [TKkk-iOSer/WeChatPlugin-MacOS#31]
开启 防撤回功能 发送test消息，撤回，此时会被拦截，如果此时关闭防撤回功能 再撤回test消息 就无法撤回

**Comment by Tasfa** [comment]
应该是 显示错误，实际上是撤回了，但是没 显示

**Comment by TKkk-iOSer** [comment]
操作是：
1.开启防撤回，发送消息并撤回。显示“拦截到撤回消息”。
2.关闭防撤回，发送消息并撤回，还是显示“拦截到撤回消息”。
 这样是么？

**Comment by Tasfa** [comment]
对，实际上撤回了，但还是显示拦截成功


Tasfa

在 2017年9月5日，下午8:56，TK <notifications@github.com<mailto:notifications@github.com>> 写道：


操作是：
1.开启防撤回，发送消息并撤回。显示“拦截到撤回消息”。
2.关闭防撤回，发送消息并撤回，还是显示“拦截到撤回消息”。
这样是么？
