### ISSUE TITLE
防撤回失效了。。。

### ISSUE THREAD

**Issue by gt-sun** [TKkk-iOSer/WeChatPlugin-MacOS#313]
是不是被官方封了啊？？

**Comment by ccchooko** [comment]
失效了。。我刚装，我自己给自己发反正是不行了

**Comment by iamsampson** [comment]
以后还是不要随便更新微信了lol

**Comment by Cat7373** [comment]
`2.3.16 (11023)` 确认问题存在

**Comment by Cat7373** [comment]
似乎不是反撤回失效了，而是自己撤回的不会被拦截了😂，再多观察下😂

**Comment by TKkk-iOSer** [comment]
现在是把自己撤回的拦截给去了。我之后在菜单栏增加个item吧，不然别人都以为是bug😂 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/commit/91fb380827d73ff282db6a7eab7f85afe6e1566f
