### ISSUE TITLE
是不是不支持最新版微信了

### ISSUE THREAD

**Issue by mmj524876614** [TKkk-iOSer/WeChatPlugin-MacOS#315]
最新版的安装之后微信没办法打开,  是不是被和谐了

**Comment by mmj524876614** [comment]
![image](https://user-images.githubusercontent.com/11512715/41816265-f67dfc0c-77b2-11e8-9bae-0070207c7e89.png)
这样子

**Comment by Cat7373** [comment]
@TKkk-iOSer `2.3.16 (11023)` 反撤回无效了😂

**Comment by Cat7373** [comment]
似乎不是反撤回失效了，而是自己撤回的不会被拦截了😂，再多观察下😂

**Comment by TKkk-iOSer** [comment]
@Cat7373 是的，现在是把自己撤回的拦截给去了。
@mmj524876614 我之后在菜单栏增加个item吧，不然别人都以为是bug😂 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/commit/91fb380827d73ff282db6a7eab7f85afe6e1566f
