### ISSUE TITLE
懒人安装之后 运行omw 直到启动微信 但是工具栏还是没有小助手

### ISSUE THREAD

**Issue by Keith4all9s** [TKkk-iOSer/WeChatPlugin-MacOS#316]
mac:~ Keith$ omw
当前微信小助手版本为 v1.7
检测到微信自动更新后删除了微信小助手
正在检查新版本……
当前已是最新版本。
开始下载微信小助手 v1.7……
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132    0   132    0     0     24      0 --:--:--  0:00:05 --:--:--    31
100 8161k    0 8161k    0     0   7800      0 --:--:--  0:17:51 --:--:-- 23335
curl: (18) transfer closed with outstanding read data remaining
[1.7.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 1.7.zip or
        1.7.zip.zip, and cannot find 1.7.zip.ZIP, period.
下载完成
开始安装微信小助手……
/usr/local/bin/omw: line 105: ./WeChatPlugin-MacOS-1.7/Other/Install.sh: No such file or directory
微信小助手安装完成。
打开微信

**Comment by lmk123** [comment]
omw 是我维护的项目，我来回答吧 😂

从错误信息上看是因为下载小助手 v1.7 的安装包的时候由于网络问题没有成功下载，可以重新运行 `omw` 尝试重新下载。

后面我会在网络出错的时候给出相应的提示的。

**Comment by lmk123** [comment]
我更新了项目，现在下载出错后会给出正确的提示：“下载失败，请稍后重试”，你可以重新安装 omw 试试。

**Comment by Keith4all9s** [comment]
成功了  很👍 厉害
