### ISSUE TITLE
自动回复消息如何保存？

### ISSUE THREAD

**Issue by ufcoxd** [TKkk-iOSer/WeChatPlugin-MacOS#327]
做个导入导出的功能？

**Comment by TKkk-iOSer** [comment]
没时间做，可以自己去沙盒里面找，都放在这里。`~/Library/Containers/com.tencent.xinWeChat/Data/Documents/TKWeChatPlugin`,里面文件夹对应不同账号，账号里面的 `TKAutoReplyModels.plist`是自动回复设置。
