### ISSUE TITLE
图片和视频消息不能防撤回？

### ISSUE THREAD

**Issue by rhodesiaxlo** [TKkk-iOSer/WeChatPlugin-MacOS#328]
![image](https://user-images.githubusercontent.com/9957924/42730527-f722dade-8828-11e8-944d-6b763d9c28fb.png)

plain text 撤回可以在撤回提示里面看到原文，image/video clip 可以看到原文件吗？如果是，怎么操作呢？

**Comment by TKkk-iOSer** [comment]
不能，如果能看到原文件就很占聊天窗口的位置了，自己往上翻聊天记录就可以了。
