### ISSUE TITLE
想问一下此项目原理

### ISSUE THREAD

**Issue by liuziangexit** [TKkk-iOSer/WeChatPlugin-MacOS#33]
请问这个项目用的是什么API，itchat还是直接反向的网页版微信？

**Comment by TKkk-iOSer** [comment]
原理大致是这样 [话说，原理是啥？ #3](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/3) itchat 是啥？

**Comment by liuziangexit** [comment]
明白，感谢。我以为是你自己做了一个微信客户端，原来是逆向了官方客户端。（itchat是一个非官方的，python上的微信个人号API
