### ISSUE TITLE
重大问题！！！！

### ISSUE THREAD

**Issue by tipshot** [TKkk-iOSer/WeChatPlugin-MacOS#333]
发送指令 比如 休眠，重启 关机，清空废纸篓之类的时候，完成过微信重启，重启只有由重新执行一次指令，又重启，然后循环下去，，，，，，，，微信版本是2.3.17,小助手版本是昨天新安装的一个，通过终端安装的。

**Comment by TKkk-iOSer** [comment]
已修复
