### ISSUE TITLE
更新微信后小助手无法安装使用

### ISSUE THREAD

**Issue by Jackeriss** [TKkk-iOSer/WeChatPlugin-MacOS#335]
1. 更新微信至Version. 2.3.17 (11255)
2. 执行 omw 提示“检测到微信自动更新后删除了微信小助手”，并开始下载安装
3. 打开微信发现没有微信小助手
4. 再次执行 omw 仍提示“检测到微信自动更新后删除了微信小助手”，又重新开始下载安装，之后循环3、4

macOS 版本：10.13.5 (17F77)

**Comment by yimiaodaren** [comment]
看来这个被wechat团队看了源码修复了

**Comment by achaorg** [comment]
更新无法使用++1

**Comment by TKkk-iOSer** [comment]
无法使用的话先卸载，在安装，使用omw没法安装的话试试普通安装

**Comment by lmk123** [comment]
我是 omw 的开发者，我也更新到了微信 Version. 2.3.17 (11255) 并使用 omw 重装了小助手，一切正常，你能提供一下运行 omw 的截图吗？

**Comment by yimiaodaren** [comment]
重新安装可以使用了

**Comment by Vannnnish** [comment]
![image](https://user-images.githubusercontent.com/38368775/43181750-37b5cbca-9011-11e8-9469-62f83d529695.png)

运行owm后就这个样子。 然后打开微信后也没看到微信小助手。  另外，你们说的重新安装是指创新安装微信小助手，还是重新安装微信。

**Comment by lmk123** [comment]
@Vannnnish 从你的截图上看，omw 在下载 v1.7.1 的安装包的时候报错了，所以其实小助手没有安装成功才对，这个提示是有问题的，我最近修复了这个提示，你可以更新一下 omw

我好奇的是为什么下载失败了你的小助手也可以使用 😂

**Comment by achaorg** [comment]
重新安装可以了，谢谢

**Comment by Jackeriss** [comment]
现在执行 omw 安装 v1.7.1 之后可以了。

**Comment by WilonQing** [comment]
我把微信安装位置修改了，install.sh 的目录 也相应的修改了但是 点击安装并重启 没有反应
