### ISSUE TITLE
 希望点击链接时直接打开系统默认浏览器，而不是弹一个微信自己的窗口，然后再点击才能打开

### ISSUE THREAD

**Issue by leyle** [TKkk-iOSer/WeChatPlugin-MacOS#337]
更新最新版微信后，傻逼微信电脑版点击链接也是弹自己的小窗了，希望增加功能，点击链接的时候，像以前一样，直接在系统默认浏览器打开。

**Comment by zqso** [comment]
同样需求+1

**Comment by RyanLiGod** [comment]
> 更新最新版微信后，傻逼微信电脑版点击链接也是弹自己的小窗了，希望增加功能，点击链接的时候，像以前一样，直接在系统默认浏览器打开。

这个其实是为了能打开美团红包之类的需要微信登录的页面

**Comment by TKkk-iOSer** [comment]
Fixed
