### ISSUE TITLE
Alfred wx 输入内容软件就崩溃退出了

### ISSUE THREAD

**Issue by llity** [TKkk-iOSer/WeChatPlugin-MacOS#340]
版本都是最新版，不知道是什么地方不兼容！谢谢

**Comment by soberzhou** [comment]
V1.7 版本 重新 omw 安装了一次，依然是崩溃

**Comment by TKkk-iOSer** [comment]
查看 菜单栏是否跟下图一样，
![image](https://user-images.githubusercontent.com/11961989/43130865-3c0b4e22-8f6a-11e8-966c-dbc29ef5860d.png)
如果不是的话，重新安装。
https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/15。 
如果 omw 安装还是不行的话，使用普通安装。也可以联系 owm 的开发者 @lmk123

**Comment by snowleopardw** [comment]
跟截图一样。普通安装。依然崩溃。

**Comment by llity** [comment]
@TKkk-iOSer 新版已解决。就是安装一次，好像聊天记录都被清空了，是bug吗？能否修复。我只开启了免密登录。

**Comment by TKkk-iOSer** [comment]
@snowleopardw 提供下微信的版本，另外请确定下是clone了今天最新版本，早上有更新了。还有就是要更新workflow。

@llity 我这边的不会，请看下微信设置里面是不是没有勾选`退出时保留聊天记录`。

**Comment by ToyYan** [comment]
alfred 输入wx两个空格，微信直接闪退。刚pull了最新版本，微信2.3.16

**Comment by TKkk-iOSer** [comment]
@ToyYan 那更新下微信吧，更新到2.3.17，可能有些接口调整了。目前的话我试了 2.3.13 跟 2.3.17 都没问题

**Comment by ToyYan** [comment]
@TKkk-iOSer 刚更新到2.3.17，并且重新安装了插件，还是闪退，我想会不会是我本地的聊天记录太多的原因，我的mac用了三年了，没有清理过聊天记录

**Comment by TKkk-iOSer** [comment]
@ToyYan 加强了搜索的判断，可以更新下试试

**Comment by TKkk-iOSer** [comment]
@ToyYan 方便提供一下微信号么？发这里或者发我邮箱都可以，我联系你然后调试下。
