### ISSUE TITLE
2个空格查看最近聊天，微信意外退出

### ISSUE THREAD

**Issue by goodluck4210** [TKkk-iOSer/WeChatPlugin-MacOS#348]
输入两个空格后微信会意外退出。

**Comment by TKkk-iOSer** [comment]
已更新，更新下小助手 & workflow

**Comment by TKkk-iOSer** [comment]
@zhaoqz  https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/18 最新的话两个空格不会闪退，只会有两种情况
* 输入wx 闪退
 * 输入wx 出现最近聊天列表

**Comment by zhaoqz** [comment]
多次实测都复现了，alfred输入『wx两个空格』 提示微信小助手搜索中，然后微信就闪退了。
上面说的版本号都是实际查看的。

因为是今天首次受用，所以都是全新安装的。
插件是用命令行按照提示安装的。
alfred插件按照文档安装的。我应该是安装的1.0版本（因为1.0是蓝色字体，很大）

刚刚选择2.0版本，在alfred中更新成功了。
现在是输入：wx就闪退了。

**Comment by zhaoqz** [comment]
2.0 安装地址 https://github.com/TKkk-iOSer/wechat-alfred-workflow/archive/v2.0.zip

**Comment by TKkk-iOSer** [comment]
微信号发我邮箱 tkk.ioser@gmail.com

**Comment by zhaoqz** [comment]
在作者的指导下搞定，结论是安装问题，其实在说明里面写了，但是文字多没有理解到，我这里再说一下。

解决方案：
1、git clone，执行Other/Install.sh 安装 插件
2、安装2.0版本的 alfred workfiow，不要下载1.0。
3、别忘记赞助作者喝杯奶茶:-)
