### ISSUE TITLE
一个闪退bug和视频持续播放bug

### ISSUE THREAD

**Issue by Sev73n** [TKkk-iOSer/WeChatPlugin-MacOS#353]
微信更新了自带浏览器 可以在点击订阅号内容之后布跳转系统浏览器
而是微信的浏览器 点击关闭这个浏览器后 必然客户端闪退
不安装插件的话没问题 所以应该是兼容问题

还有就是安装了插件之后 点击任何一个对话中的视频
关闭后后台还是会继续播放声音
知道整个视频全部播放完毕
想要停止只能强制退出整个微信客户端才行

**Comment by TKkk-iOSer** [comment]
刚刚试了…都没遇到过，微信版本是 2.3.13 跟 2.3.17.18…从网页下载的 https://mac.weixin.qq.com/

**Comment by Sev73n** [comment]
奇怪 我的客户端就可以复现这个问题 而且我卸载了小助手 登录的时候还是不用扫码 是不是表示还有残留？
我把omw和小助手都卸载了 还是有问题 微信是商店下载的
是不是我哪里没有清理干净啊

**Comment by Sev73n** [comment]
排查出来了 和mySIMBL冲突 这个插件有个功能是任意窗口置顶
上次更新是17年了 估计是哪里窗口不兼容
屏蔽了就好了
