### ISSUE TITLE
网易云音乐命令失效

### ISSUE THREAD

**Issue by SadWood** [TKkk-iOSer/WeChatPlugin-MacOS#355]
execution error: “System Events”遇到一个错误：“osascript”不允许辅助访问。 (-1719)
辅助访问已经打开。

**Comment by Wangmafei** [comment]
execution error: “System Events”遇到一个错误：“osascript”不允许辅助访问。 (-1719)

**Comment by YangAidi** [comment]
同遇到这个问题

**Comment by CCBrother** [comment]
我也遇到了

**Comment by edisonX** [comment]
me too~
