### ISSUE TITLE
使用 Safari 打开公众号文章

### ISSUE THREAD

**Issue by CheerfulDL** [TKkk-iOSer/WeChatPlugin-MacOS#358]
微信 Version. 2.3.17 (11255)
更新之后，公众号文章都是使用微信内置浏览器进行查看，希望可以把它改回原来的 Safari 打开

**Comment by SIGAOYI** [comment]
楼上+1
申请阻止微信转链，屏蔽微信内置浏览器。
请你喝一个月咖啡！！

**Comment by SIGAOYI** [comment]
#337 同一个Issue

**Comment by TKkk-iOSer** [comment]
@SIGAOYI @CheerfulDL  已加，开关在菜单栏
