### ISSUE TITLE
希望 消息回复，和接受可以调用接口

### ISSUE THREAD

**Issue by oyoy8629** [TKkk-iOSer/WeChatPlugin-MacOS#359]
功能非常强大，我很喜欢，但是我不懂objectc
希望楼主能优化一个功能
可以将 发送和回复都请求自定义接口。

比如像其他机器人一样，可以通过接口去做一些智能回复，如天气等。。。

**Comment by TKkk-iOSer** [comment]
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/373
