### ISSUE TITLE
KillAll命令有毒~~~

### ISSUE THREAD

**Issue by lx36301766** [TKkk-iOSer/WeChatPlugin-MacOS#362]
这个命令存在很严重的bug啊，一旦用了微信可能再也启动不起来了。就在对自己的聊天框中输入KillAll，所有应用都会被关闭，包括微信。然后再次点击微信启动，还没启动起来马上又被关闭，估计是识别到了上一次输入的KillAll命令，还没来得及清除指令，微信就被关闭了，这样就陷入一个死循环中永远启动不起来了~~~

**Comment by TKkk-iOSer** [comment]
微信的API改了，之前的版本同步一次就不会同步，新版本好像会一直同步。
