### ISSUE TITLE
是否有内存泄露的可能

### ISSUE THREAD

**Issue by ivoth** [TKkk-iOSer/WeChatPlugin-MacOS#369]
系统长期不关机,只休眠,微信占用内存 1.91GB, 压缩: 1.84GB
我记得没有使用之前的微信是不会暂时这么多的

小助手: 1.7.1
设备类型：Macmini7,1
系统版本：版本 10.13.6（版号 17G65）
微信版本：Version. 2.3.17 (11255)  v2.3.17.16 (0x12031110)

**Comment by TKkk-iOSer** [comment]
检查了下，有的地方已经修复了。如果有内存泄露的，欢迎pr
