### ISSUE TITLE
有没有API版本

### ISSUE THREAD

**Issue by chenyanmo** [TKkk-iOSer/WeChatPlugin-MacOS#373]
如题。可不可以脱离客户端？

**Comment by TKkk-iOSer** [comment]
可以使用 [wechat-alfred-workflow](https://github.com/TKkk-iOSer/wechat-alfred-workflow)，里面的话提供了 
* 微信快速发送消息 
* 快速搜索微信好友、群聊
* 快速查看最近聊天列表
* 查看聊天记录
* 预览视频、表情、图片、网址等消息
基本上能摆脱微信客户端了。算是我插件中使用频率最高的了。里面也有相对于的API，也可以自己封装起来。
~~(另外，这都能遇到熟人😂~~
