### ISSUE TITLE
是否可以转载至个人博客？还有getHelp指令失效问题。

### ISSUE THREAD

**Issue by StudentKe** [TKkk-iOSer/WeChatPlugin-MacOS#375]
请问是否可以转载至个人博客？注明作者并带链接。
还有getHelp指令失效。

**Comment by TKkk-iOSer** [comment]
* 可以
* getHelp是啥？

**Comment by StudentKe** [comment]
- 远程控制mac里面的
- 获取指令的 command
![image](https://user-images.githubusercontent.com/39193022/44884164-dc1dcd00-acec-11e8-984b-e23230a3097a.png)

**Comment by TKkk-iOSer** [comment]
Fixed
