### ISSUE TITLE
如果没有开启消息防撤回，这里会循环调用自己

### ISSUE THREAD

**Issue by albertofwb** [TKkk-iOSer/WeChatPlugin-MacOS#376]
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/blob/c8b782628d69e098db647a527d3457f103e77db7/WeChatPlugin/Sources/Hook/WeChat%2Bhook.m#L127

**Comment by xieao100** [comment]
最新版本 alfred输入指令闪退 求更新

**Comment by albertofwb** [comment]
我实际单步调试了下，发现并没有循环调用自己。但是不明白为什么

**Comment by albertofwb** [comment]
这是 Runtime 中的 Method Swizzling.
在一开始的时候，就已经使用 tk_hookMethod(objc_getClass("MessageService"), @selector(onRevokeMsg:), [self class], @selector(hook_onRevokeMsg:));
进行两个方法实现地址互换，所以当
调用 hook_onRevokeMsg 的时候，其实是调用 [MessageService onRevokeMsg:],
调用onRevokeMsg 的时候，其实是调用[self hook_onRevokeMsg].所以不会递归。相关的逻辑可以搜下 OC 的 Runtime 特性 Method Swizzling.
