### ISSUE TITLE
报个bug

### ISSUE THREAD

**Issue by jiangll97** [TKkk-iOSer/WeChatPlugin-MacOS#380]
在微信2.3.18版本中的Alfred中输入 wx + 任何字符会闪退～

**Comment by zqso** [comment]
我也有相同问题。
1. 微信2.3.18
2. 最新Alfred Workflow
3. Mojave public beta 8

附 Crash Report:
[WeChat_2018-09-08-132909_Z.txt](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/files/2363036/WeChat_2018-09-08-132909_Z.txt)

**Comment by dreistein543** [comment]
也是跟楼上相同问题，另外，似乎无法取消小助手中的免认证登陆功能

**Comment by RoachCn** [comment]
+1 同样问题

**Comment by whimthen** [comment]
同样的问题，免认证关闭不起作用，搜索闪退，Mojava beta

**Comment by sfdye** [comment]
https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/25#issuecomment-430486519
