### ISSUE TITLE
可以自己在远程控制里加入功能吗？

### ISSUE THREAD

**Issue by hhyvs111** [TKkk-iOSer/WeChatPlugin-MacOS#385]
能说一下对应的位置在哪吗？

**Comment by TKkk-iOSer** [comment]
~/Library/Containers/com.tencent.xinWeChat/Data/Documents/TKWeChatPlugin/用户id/

**Comment by hhyvs111** [comment]
> ~/Library/Containers/com.tencent.xinWeChat/Data/Documents/TKWeChatPlugin/用户id/

我是说代码，不是列表。找了半天没找到，比如killqq的代码在哪？

**Comment by TKkk-iOSer** [comment]
你看下里面的文件名在全局搜下不就知道了。
然后如果你改了代码没有删掉或者替换这些也没用，这些会缓存。
最后相关代码与逻辑搜下 RemoteControl 我注释都有写了，自己看。
