### ISSUE TITLE
alfred 输入wx+任意字符 回车后微信闪退

### ISSUE THREAD

**Issue by one-meter** [TKkk-iOSer/WeChatPlugin-MacOS#388]
是不是没有校验 后台异常了

**Comment by hexid26** [comment]
确实出现了问题。导致微信崩溃退出。
挺好用的功能，等大神 fix。

**Comment by catoldcui** [comment]
@one-meter @hexid26 也出现了同样问题。我这里直接run omw重新安装后正常了。

**Comment by hexid26** [comment]
@catoldcui 不好意思 ，你的 run omw 是个什么操作，不太明白。。。

**Comment by catoldcui** [comment]
@hexid26 https://github.com/lmk123/oh-my-wechat 这个cmd

**Comment by hexid26** [comment]
@catoldcui 不是这边插件的问题，应该是 Alfred 的 workflow 和新版本的微信有点不兼容。此问题应该在这里：
https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/25
等待 TK 解决。

**Comment by catoldcui** [comment]
@hexid26 哦哦，这样。我也出现了这个问题，谢谢提醒哈。

**Comment by sfdye** [comment]
原问题已解决 
https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/25#issuecomment-430486519

**Comment by TKkk-iOSer** [comment]
之后 alfred相关的问题可以去 https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues 提
