### ISSUE TITLE
请求更新。。。。

### ISSUE THREAD

**Issue by xieao100** [TKkk-iOSer/WeChatPlugin-MacOS#394]
1、请求修复alfred 输入wx+任意字符闪退问题
2、请求增加阻止微信新版本提示功能
多谢了 大佬两个多月没上github 干嘛去了
@TKkk-iOSer

**Comment by sfdye** [comment]
已解决 
https://github.com/TKkk-iOSer/wechat-alfred-workflow/issues/25#issuecomment-430486519
