### ISSUE TITLE
我电脑之前装好了，过段时间自己没了，然后就再怎么也重装不上了，求助啊

### ISSUE THREAD

**Issue by a1062779714** [TKkk-iOSer/WeChatPlugin-MacOS#395]
重新安装提示这个：/Users/hebinbin/Downloads/WeChatPlugin-MacOS-master 3/Other/Install.sh: line 41: /Users/hebinbin/Downloads/WeChatPlugin-MacOS-master: is a directory
hebinbindeMacBook-Pro:~ hebinbin$ 

然后我卸载提示这个：Last login: Wed Oct 10 09:15:57 on ttys000
hebinbindeMacBook-Pro:~ hebinbin$ /Users/hebinbin/Downloads/WeChatPlugin-MacOS-master\ 3/Other/Uninstall.sh 
卸载失败，请到 /Applications/WeChat.app/Contents/MacOS 路径，删除 WeChatPlugin.framework、WeChat 两个文件文件，并将 WeChat_backup 重命名为 WeChat
\n\t卸载成功
hebinbindeMacBook-Pro:~ hebinbin$ 

但是我再次卸载又会变成
提示我未发现微信小助手

**Comment by TKkk-iOSer** [comment]
已更新
