### ISSUE TITLE
有小哥更新了macos mojave最新系统10.14.**版本的嘛？想知道是否能正常运行本插件？

### ISSUE THREAD

**Issue by iszhuzhi** [TKkk-iOSer/WeChatPlugin-MacOS#396]
有小哥更新了macos mojave最新系统10.14.**版本的嘛？想知道是否能正常运行本插件？

**Comment by Jiangvoid** [comment]
目前没有发现什么问题，正常使用。

**Comment by leo-fengchao** [comment]
最新系统，最新微信版本，都可以正常使用

在 2018年10月11日，下午3:34，Jiangvoid <notifications@github.com<mailto:notifications@github.com>> 写道：


目前没有发现什么问题，正常使用。

**Comment by iszhuzhi** [comment]
> 目前没有发现什么问题，正常使用。

哈哈，感谢小哥！

**Comment by iszhuzhi** [comment]
> 最新系统，最新微信版本，都可以正常使用在2018年10月11日，下午3：34，Jiangvoid <notifications@github.com <mailto：notifications@github.com >>写道：目前没有发现什么问题，正常使用。 - 你收到这个是因为你订阅了这个帖子。直接回复此电子邮件，在GitHub上查看< [https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTKkk-iOSer%2FWeChatPlugin-MacOS%2Fissues%2F396% 23issuecomment-428851670和数据= 02％7C01％7C％7Cab58b99d00b340edef3708d62f4becbd％7C84df9e7fe9f640afb435aaaaaaaaaaaa％7C1％7C0％7C636748400463816475＆SDATA = Bdm2rPVy7k9EbtfZr6juP3umvvo9Sw1Z7RfRwmkqYFw％3D＆保留= 0](https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTKkk-iOSer%2FWeChatPlugin-MacOS%2Fissues%2F396%23issuecomment-428851670&data=02%7C01%7C%7Cab58b99d00b340edef3708d62f4becbd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636748400463816475&sdata=Bdm2rPVy7k9EbtfZr6juP3umvvo9Sw1Z7RfRwmkqYFw%3D&reserved=0) >，或静音螺纹<[https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIjIiq1dqYtZl2oV0pbU-7yp-iBgySkEks5ujvRsgaJpZM4XW7t9&data=02%7C01%7C%7Cab58b99d00b340edef3708d62f4becbd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1 ％7C0％7C636748400463816475＆sdata = IwiHQnhkBAFoxdoUOhFEUbxRrW50SEXZHktxihzpMHM％3D＆reserved = 0](https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIjIiq1dqYtZl2oV0pbU-7yp-iBgySkEks5ujvRsgaJpZM4XW7t9&data=02%7C01%7C%7Cab58b99d00b340edef3708d62f4becbd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636748400463816475&sdata=IwiHQnhkBAFoxdoUOhFEUbxRrW50SEXZHktxihzpMHM%3D&reserved=0) >。

感谢小哥！
