### ISSUE TITLE
能不能留一个开发入口给不会oc的开发者

### ISSUE THREAD

**Issue by dcsunny** [TKkk-iOSer/WeChatPlugin-MacOS#397]
大概留一个像微信公众号一样，留一个开发设置的http入口来接收和回复消息，这样给不会oc的开发者能够依靠这个插件去开发

**Comment by Lujango** [comment]
可以有

**Comment by TKkk-iOSer** [comment]
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/373

**Comment by dcsunny** [comment]
不太希望借助alfred实现的~
