### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Laniakeacl** [TKkk-iOSer/WeChatPlugin-MacOS#399]
<img width="837" alt="2018-10-15 15 37 40" src="https://user-images.githubusercontent.com/37819930/46936257-66997080-d090-11e8-8f37-d579393a107a.png">

**Comment by TKkk-iOSer** [comment]
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/blob/master/Install.md
