### ISSUE TITLE
【需求】希望加个callback

### ISSUE THREAD

**Issue by zhangshanhai** [TKkk-iOSer/WeChatPlugin-MacOS#4]
当微信客户端受到消息，文本 图片来自名片等，公众号文章推送等， 向一个url 地址进行 请求。比如好友/群聊/公众号发来文章，将文章信息 发到url上，我能做一些处理。

我更想 让微信客户端变成傀儡。

**Comment by TKkk-iOSer** [comment]
可以实现，就是跟自动回复的性质差不多，只不过不是回复给好友而是回复到某个网址。不过感觉这个日常需求不大。

**Comment by zhangshanhai** [comment]
需求很高。比如我，
采集微信公众号的文章，那么公众号/群/好友 发了文章，就发送到url上，我就能搞到。

这些方便跟自己开发的 程序集成。

**Comment by lujqme** [comment]
需求很高，这样的话也方便开发者最大可能地利用微信

**Comment by TKkk-iOSer** [comment]
@zhangshanhai 看来是因为我比较少用微信看文章的原因吧，所以就觉得少用。具体说说是什么需求吧，是要向url发送什么？文章的链接？

**Comment by lujqme** [comment]
需求是这样的：

- 当收到好友消息时，把发消息的好友信息（比如昵称，ID等）以及消息时间消息内容作为POST请求的DATA，这种情况下回调函数是个POST请求，请求的URL是我自己的服务器，所以我就能通过配置服务器对这个消息做出响应。
- 当收到公众号文章时，可以把文章标题和URL以及发送这篇文章的公众号名称作为POST请求的DATA或者GET请求的QUERY发送到我指定的URL，这个URL是我的服务器，然后我就能控制服务器进行后续处理。

我的需求大概如此，还需看看其他朋友们的反馈。十分感谢。

**Comment by reechou** [comment]
请问这个实现了吗
