### ISSUE TITLE
自动回复可否加入不回复公众号的选项

### ISSUE THREAD

**Issue by thomasxu1991** [TKkk-iOSer/WeChatPlugin-MacOS#40]
现在只有屏蔽群聊，刚刚开启了自动回复后，有几个公众号也被自动回复了。

**Comment by TKkk-iOSer** [comment]
已修复，屏蔽公众号自动回复。（~~感觉没必要多个公众号选项了，因为之后还要加个私聊自动回复开关选项~~）
