### ISSUE TITLE
控制网易云音乐报错

### ISSUE THREAD

**Issue by 81pla** [TKkk-iOSer/WeChatPlugin-MacOS#400]
控制网易云音乐报错

已经给微信权限了

execution error: “System Events”遇到一个错误：不能获得“menu bar 1 of process "NeteaseMusic"”。无效的索引。 (-1719)

**Comment by TKkk-iOSer** [comment]
安全性与隐私-辅助功能，检查下是否有给微信权限，有的话还是不行再给脚本编辑器权限
