### ISSUE TITLE
申请自动回复加入群邀请功能

### ISSUE THREAD

**Issue by wongyongcheng** [TKkk-iOSer/WeChatPlugin-MacOS#401]
自动回复功能是否可以设置自动回复选择好的一个群邀请功能。
例如：回复 加群 ，发送设置好的  A群名称 - 序号、B群名称 - 序号，好友回复 对应的序号，发送对应序号的群邀请过去，这样好友就能自动加入该群。

**Comment by TKkk-iOSer** [comment]
这个不加了，有点微商性质
