### ISSUE TITLE
控制网易云问题

### ISSUE THREAD

**Issue by dcr327** [TKkk-iOSer/WeChatPlugin-MacOS#402]
隐私-辅助功能 已经添加。远程控制网易云功能时，弹窗
【“微信”想要控制“微信”。允许控制将提供对“微信”中文稿和数据的访问权限，以及允许在该应用中执行操作。】  选项：（不允许） （好）

**Comment by TKkk-iOSer** [comment]
那就允许，如果还是不行的话，就加上脚本编辑器

**Comment by dcr327** [comment]
每次操作都要允许。把微信和脚本编辑器都添加了依然不行

**Comment by szhzju** [comment]
同样的问题，求问怎么解决
