### ISSUE TITLE
微信2.3.19版本 微信长期显示为所在页面第一个

### ISSUE THREAD

**Issue by luludada** [TKkk-iOSer/WeChatPlugin-MacOS#406]
切换其他app 微信都一直在屏幕第一个且不能隐藏
Mac上划显示所有app，微信自动消失

**Comment by xieao100** [comment]
微信更新了 求更新@

**Comment by luludada** [comment]
这个bug还在吧

**Comment by TKkk-iOSer** [comment]
@luludada 菜单栏检查下是否误触了 微信窗口置顶 的开关
![image](https://user-images.githubusercontent.com/11961989/47469184-25dcec80-d832-11e8-8a25-542904612f0f.png)

**Comment by luludada** [comment]
> @luludada 菜单栏检查下是否误触了 微信窗口置顶 的开关
> ![image](https://user-images.githubusercontent.com/11961989/47469184-25dcec80-d832-11e8-8a25-542904612f0f.png)

看到了 谢谢
