### ISSUE TITLE
最新版微信和防撤回插件，alfred 输入wx 没有头像预览了

### ISSUE THREAD

**Issue by xieao100** [TKkk-iOSer/WeChatPlugin-MacOS#407]
![image](https://user-images.githubusercontent.com/15829332/47402154-c1a92280-d776-11e8-8c0b-a709a99cdc6e.png)

如图所示，求更新修复。
0、头像没有预览了
1、而且搜索功能失效了，比如我搜索文件传输助手 列表中显示的还是所有人
2、使用workflow插件搜索后微信cpu占用暴增，mac风扇飞速运转！
![image](https://user-images.githubusercontent.com/15829332/47402417-113c1e00-d778-11e8-8568-6d8238bf8f82.png)

@TKkk-iOSer

**Comment by sfdye** [comment]
+1 所有的我都有

**Comment by TKkk-iOSer** [comment]
微信搜索机制改了，至于为什么CPU会飙这么高，是因为搜索不到陷入无限空循环了，之后修复下。

**Comment by TKkk-iOSer** [comment]
已修复

**Comment by xieao100** [comment]
@TKkk-iOSer 搜索什么的修复了 就差个alfred 搜索wx+ 联系人没有头像预览了

**Comment by xieao100** [comment]
@sfdye 为什么我的不可啊 难道要重新卸载再安装

**Comment by sfdye** [comment]
你试试 重装插件 重装微信 重启微信

**Comment by xieao100** [comment]
重装了还是不行

**Comment by xieao100** [comment]
@sfdye 全部重装了一遍 卸载了微信和小助手 清理重启 我甚至连alfred都重装了 还是不行

**Comment by xieao100** [comment]
降级了可以了。求个屏蔽更新提示的功能！

**Comment by TKkk-iOSer** [comment]
屏蔽更新的…我这边一直没有出现要我更新的弹窗提示

**Comment by xieao100** [comment]
左上角点击微信，检查更新，就会有弹窗提示了，前提是你是旧版本

**Comment by zwhGithub** [comment]
微信头像没有，然后alfred  wx 后面切换输入法，alfred会闪退。

**Comment by zwhGithub** [comment]
请问你们有出现这个问题吗，或者有修复的方法吗？

**Comment by TKkk-iOSer** [comment]
已修复，请更新小助手到最新 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/archive/master.zip
