### ISSUE TITLE
微信 Mac 2.3.19 更新后插件已失效

### ISSUE THREAD

**Issue by snakejordan** [TKkk-iOSer/WeChatPlugin-MacOS#411]
如题，刚刚更新的微信版本。

**Comment by Little-song** [comment]
在线更新好慢啊，还有什么办法更新啊？

**Comment by sfdye** [comment]
作者已经更新了 从master安装即可 目前搜索还有问题 其他可以用

**Comment by snakejordan** [comment]
刚才仔细看了看，发现确实有更新，不过好像没合并到懒癌安装版呢，昨天尝试懒癌安装板没成功，试一下 master 安装。

**Comment by sfdye** [comment]
是的 brew支持也在讨论中了 见 #405

**Comment by snakejordan** [comment]
> 是的 brew支持也在讨论中了 见 #405

已成功，感谢提醒，close 掉了。

**Comment by snakejordan** [comment]
> 在线更新好慢啊，还有什么办法更新啊？

下载 master 的安装包，Other 下的 Install.sh 安装。
