### ISSUE TITLE
希望远程控制加一个静音 MacBook 的功能

### ISSUE THREAD

**Issue by snakejordan** [TKkk-iOSer/WeChatPlugin-MacOS#412]
远程控制挺好的，但是对我个人来说都不太实用。

个人最需要的是一个静音 MacBook 的功能，因为基本上我的 Mac 常年开机，睡觉的时候忘了静音的话微信总会响，这样很影响，要是能一键静音，就太好了。

**Comment by dengxiaozhen** [comment]
睡觉 MacBook 盖子不合上的吗

**Comment by snakejordan** [comment]
> 睡觉 MacBook 盖子不合上的吗

确实不合上，所有设备都是外接的，睡觉也不习惯关掉了。

**Comment by TKkk-iOSer** [comment]
感谢 @HansSJTU 完成
