### ISSUE TITLE
为啥每次更新微信就消失了？

### ISSUE THREAD

**Issue by olafchou** [TKkk-iOSer/WeChatPlugin-MacOS#414]
请问更新微信之后怎么操作，助手每次都会消失

**Comment by olafchou** [comment]
> 更新后就重新安装助手啊，找到other里的install，再次执行一遍

但是我是懒人安装，他给我安装到下载里面了，我一般会删除下载里面的东西，那咋办？？？

**Comment by hhyvs111** [comment]
> > 更新后就重新安装助手啊，找到other里的install，再次执行一遍
> 
> 但是我是懒人安装，他给我安装到下载里面了，我一般会删除下载里面的东西，那咋办？？？

那你再重新安装吧，我刚才更新了微信，然后重新安装了助手，没问题。

**Comment by TKkk-iOSer** [comment]
动态库注入，如果更新了微信，修改后的微信二进制文件就会替换成微信的官方的，所以就失效。
