### ISSUE TITLE
Alfred没效果  

### ISSUE THREAD

**Issue by szweee** [TKkk-iOSer/WeChatPlugin-MacOS#415]
不知道为什么 
<img width="596" alt="2018-10-27 3 57 06" src="https://user-images.githubusercontent.com/20777870/47601307-16f86480-da01-11e8-84be-fd0fe69c9d63.png">
<img width="434" alt="2018-10-27 3 57 23" src="https://user-images.githubusercontent.com/20777870/47601313-1d86dc00-da01-11e8-93c2-444225d59db0.png">

**Comment by TKkk-iOSer** [comment]
先安装workflow https://github.com/TKkk-iOSer/wechat-alfred-workflow

**Comment by szweee** [comment]
好的  谢谢啦
