### ISSUE TITLE
免认证功能在V2.3.18版本失效！

### ISSUE THREAD

**Issue by FrizzleFur** [TKkk-iOSer/WeChatPlugin-MacOS#416]
Mac微信版本：Version. 2.3.18 (11431)
OSX版本： 10.13.4
重新使用免认证功能登录微信，会一直卡在这个画面
![image](https://user-images.githubusercontent.com/16328879/47601437-32646f00-da03-11e8-82fa-955f3d882d0e.png)
貌似加了验证，求解

**Comment by TKkk-iOSer** [comment]
1. 先使用普通安装更新插件。
2. 还是卡在这的话先切换账号然后再试下。
3. 还是不行那就升级微信

**Comment by FrizzleFur** [comment]
最新版本V2.3.22 可以~
