### ISSUE TITLE
CPU使用率100%

### ISSUE THREAD

**Issue by whimthen** [TKkk-iOSer/WeChatPlugin-MacOS#419]
在我使用插件期间，CPU使用率经常达到100%

**Comment by dengxiaozhen** [comment]
是否播放视频了

**Comment by whimthen** [comment]
没有播放视频

狐狸 <notifications@github.com>于2018年10月30日 周二上午10:56写道：

**Comment by catoldcui** [comment]
同100%
复现：
1. 关闭Alfred支持
2. 再打开Alfred支持后，CPU直奔100%。再关闭也降不下来，只能kill进程。

**Comment by TKkk-iOSer** [comment]
之前修复了，忘了关

**Comment by liximomo** [comment]
哪个 commit 修复的？很好奇是什么原因引起的。

**Comment by svcvit** [comment]
1.7.5 现在出现cpu 100%，这个现在又出现了。 @TKkk-iOSer

**Comment by ehlxr** [comment]
我这儿使用也是 100% cpu
