### ISSUE TITLE
不能同步消息

### ISSUE THREAD

**Issue by yanhuiandy** [TKkk-iOSer/WeChatPlugin-MacOS#420]
安装插件后不能同步消息
WeChat：Version. 2.3.19 (11654)
WeChatPlugin-MacOS：Version. 1.7.3
macOS Mojave：Version. 10.14.1 Beta (18B73a)

**Comment by byemaxx** [comment]
关闭免认证登录就好了.

**Comment by yanhuiandy** [comment]
还有没有更好的方案了？😊
