### ISSUE TITLE
有没有可能将自动回复接口化？

### ISSUE THREAD

**Issue by bojone** [TKkk-iOSer/WeChatPlugin-MacOS#423]
我想将自动回复对接一个现成的机器人接口（post方式），根据不同的内容自动回复不同的答案，请问要怎么做呢？

**Comment by TKkk-iOSer** [comment]
这个的话可以使用其他的 python 库，目前没有这个功能

**Comment by bojone** [comment]
机器人接口部分用python没有问题，但是我怎么将这个回复接口跟WeChatPlugin串联起来呢？

**Comment by Lujango** [comment]
python有基于web微信的库，直接登陆就可以发消息

**Comment by bojone** [comment]
就是因为web微信可能存在各种限制，所以才想着寻求pc微信的解决方案的呀。
