### ISSUE TITLE
网易云控制修改指令后，无法再进行控制

### ISSUE THREAD

**Issue by dawangraoming** [TKkk-iOSer/WeChatPlugin-MacOS#43]
![截图](https://user-images.githubusercontent.com/7522275/30196753-960d3906-9495-11e7-8bac-c24fe7103f98.png)

修改指令后，指令无法生效，目前进行过尝试
1、重启网易云，但不重启微信，发送指令--无效
2、加载列表后再重启网易云，进入私人电台，发送指令--无效
3、重启微信与网易云，发送指令--无效
4、尝试旧指令`TK-Next`--无效

但没有修改的指令，如退出WeChat的`TK-WeChat`可以正常执行。

------
微信版本：2.3.2(9414)
网易云版本：1.5.7 (586)
MacOS版本：10.12.6 (16G29)

**Comment by TKkk-iOSer** [comment]
除了网易云，其他的远程控制是否有效？若有的话，去看下隐私设置是否有勾选微信…另外私人电台的话没有上一曲的控制。

请问下你的自动回复功能是否有效呢？有人跟我反馈说10.12.6的无法自动回复。

**Comment by dawangraoming** [comment]
确实是隐私被取消导致的，但是我之前勾选了，被系统给取消了？
关于自动回复，我测试了下，`消息内容==关键字` 可以正常回复，若是信息中只是包含匹配的字符是无法自动回复的

**Comment by TKkk-iOSer** [comment]
@dawangraoming 匹配的字符指的是… `在||在么`这样就无法自动回复了么？

**Comment by dawangraoming** [comment]
比如关键字是“在么”
消息内容为“你在么”，这种是无法自动回复的

**Comment by TKkk-iOSer** [comment]
这个确实没有，多谢反馈。
