### ISSUE TITLE
求助：屏蔽微信检查更新的功能

### ISSUE THREAD

**Issue by JimLee1996** [TKkk-iOSer/WeChatPlugin-MacOS#435]

**Comment by wenbobao** [comment]
同求

**Comment by yangnaihua** [comment]
App store --> 偏好设置---> 取消自动更新（App Store 将自动下载并安装 App 更新），就可以了 @wenbobao @JimLee1996

**Comment by JimLee1996** [comment]
@yangnaihua 好像和 appstore 无关，是微信自带的更新功能

**Comment by xiebruce** [comment]
@yangnaihua 有些人是官网下载dmg包安装的也会更新，是微信自己的更新，不过我倒是觉得有更新就更新啊，又不像系统更新要很久，重装个插件很简单

**Comment by a83988029** [comment]
@xiebruce 现在你就不会这么说了

**Comment by TKkk-iOSer** [comment]
已新增 非APP Store 下载的禁止更新弹窗提醒
