### ISSUE TITLE
没有使用系统浏览器选项

### ISSUE THREAD

**Issue by Sev73n** [TKkk-iOSer/WeChatPlugin-MacOS#436]
我帮我朋友安装的时候发现他有了一个使用系统浏览器打开链接的选项，而我却没有，我们都是用owm功能安装的最新1.7.3版本 我试着卸载重新安装了，一样是没有这个功能，是因为我哪里操作不对了吗

**Comment by TKkk-iOSer** [comment]
可以使用普通安装安装下。`cd ~/Downloads && rm -rf WeChatPlugin-MacOS && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git --depth=1 && ./WeChatPlugin-MacOS/Other/Install.sh`

**Comment by Sev73n** [comment]
成功解决了 感谢感谢！！！

**Comment by xiebruce** [comment]
@Sev73n 不错不错，你不在这里提，我还不知道有这个选项呢，哈哈

**Comment by TKkk-iOSer** [comment]
@xiebruce 看来你们都不看功能跟更新日志的啊😂
![image](https://user-images.githubusercontent.com/11961989/48398426-b20c7080-e75b-11e8-95a4-f9e14667682e.png)

**Comment by xiebruce** [comment]
@TKkk-iOSer  哈哈，我们查看的速度跟不上你更新的速度，太腻害了

**Comment by TKkk-iOSer** [comment]
@xiebruce 别怕，今后打算一年两更了，保证跟得上

**Comment by xiebruce** [comment]
@xiebruce 哈哈，一年两更倒不至于吧，看情况，有痛点需求就更一下也是可以的，我是无所谓，我只要有防撤回功能就OK的了，其它功能目前我还没用上，辛苦你写这么多功能了！这已经9410个star了，再多写俩功能就破万了哈哈，其实估计是你没宣传一下，不然早就破万了，如果以后需要找下一份工作，这1w star很有份量啊，直接说老子github的项目都是上万的star哈哈

**Comment by xiebruce** [comment]
@TKkk-iOSer 哦，除了防撤回，我还用了『用本机浏览器打开』这个功能，哈哈
