### ISSUE TITLE
新需求：自动保存所有聊天记录到指定文件

### ISSUE THREAD

**Issue by Co2333** [TKkk-iOSer/WeChatPlugin-MacOS#438]
就是保存选中聊天或全部聊天的文件以文本文件的格式保存到一个位置，方便其他launchdaemon来获取资源并且整理分析。有些群里面会发影片资源的链接，希望能够自动获取。

**Comment by TKkk-iOSer** [comment]
颗粒度小，普通用户用不到这功能。
