### ISSUE TITLE
新需求：点击微信聊天记录自动回到聊天窗口对应区域

### ISSUE THREAD

**Issue by xiebruce** [TKkk-iOSer/WeChatPlugin-MacOS#440]
手机搜索到聊天记录后，点击一下是可以回到聊天窗口对应位置的，但Mac客户端却不可以，具体表现在：
1、未搜索时，无法点击回到聊天窗口
2、输入关键字搜索到聊天内容时，点击聊天内容中的`view text`也只是在历史记录窗口跳转一下，不能跳转到聊天窗口对应位置

**Comment by TKkk-iOSer** [comment]
直接在聊天记录里查看上下文就好了吧，如果是跳转到聊天窗口，那么你如果搜索2年前的记录，这时候要看对方发送什么消息，岂不是要一直往下滚很久才可以。

**Comment by xiebruce** [comment]
@TKkk-iOSer 这个问题确实不知道哈哈，因为手机微信也是跳转到聊天窗口的，没试过搜索两年前的消息会怎样哈哈
