### ISSUE TITLE
Alfred中头像显示不出来的bug

### ISSUE THREAD

**Issue by SadWood** [TKkk-iOSer/WeChatPlugin-MacOS#441]
换了新Mac，重新安装了，发现在Alfred中，输入wx指令后，头像都显示不出来了，不知道是什么原因。

**Comment by cnxiekun** [comment]
me2

**Comment by xieao100** [comment]
我也是这样的

**Comment by zhanghan0529** [comment]
+1

**Comment by xieao100** [comment]
@TKkk-iOSer

**Comment by TKkk-iOSer** [comment]
请说明下微信、mac、小助手版本，目前我这不是不会。

**Comment by SadWood** [comment]
> 请说明下微信、mac、小助手版本，目前我这不是不会。

目前我的是微信2.3.19，Mac：10.14.2，小助手1.7.5，时间有点久远了，之前就有这个问题。

**Comment by zhanghan0529** [comment]
微信2.3.22 mac：10.14.2 小助手1.7.5 刚才又重新导入alfred,头像还是没有显示。。

**Comment by xieao100** [comment]
> > 请说明下微信、mac、小助手版本，目前我这不是不会。
> 
> 目前我的是微信2.3.19，Mac：10.14.2，小助手1.7.5，时间有点久远了，之前就有这个问题。

我也是之前就存在 从那个版本开始起往后都没有头像了

**Comment by TKkk-iOSer** [comment]
已修复，请更新小助手到最新 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/archive/master.zip
