### ISSUE TITLE
新需求：增加聊天截图

### ISSUE THREAD

**Issue by zgqq** [TKkk-iOSer/WeChatPlugin-MacOS#445]
和某人的聊天截成长图

**Comment by xiebruce** [comment]
这个需求有点不靠谱，好几年的聊天，要截到什么时候？图肯定存不下，另外，久远的图都没了(或者被清了)，这个需求，你可以自己安装xnip截图工具来截取，它的滚动截取是先选定区域，然后自己滚动截的，很好用，要截多长截多长。

**Comment by zgqq** [comment]
@xiebruce 这个我知道，还是太麻烦了

**Comment by xieao100** [comment]
没啥意义

**Comment by fanyuexiang** [comment]
不可取

**Comment by cwwise** [comment]
这个并没有什么意义

**Comment by TKkk-iOSer** [comment]
请使用 Xnip
