### ISSUE TITLE
有撤回消息后打开微信崩溃

### ISSUE THREAD

**Issue by bruceCzK** [TKkk-iOSer/WeChatPlugin-MacOS#45]
![image](https://user-images.githubusercontent.com/8399711/30204873-922e3e92-94b9-11e7-8630-e9d6e116ac8b.png)
完整错误日志
https://pastebin.com/Nq7a5nv1

**Comment by TKkk-iOSer** [comment]
能否打开`实用工具-控制台`(如下图)，然后在输入框中输入`wechat`,在点击微信崩溃前先清除一下，然后崩溃了把当前的所有log拷贝出来看下？

![WX20170910-011908@2x.png](http://upload-images.jianshu.io/upload_images/965383-1b76fdfe5af5f21f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by cs50Mu** [comment]
同样的问题，按照你上面说的，复制log如下：

default	16:41:54.976979 +0800	WeChat	++++++++ WeChatPlugin loaded ++++++++
default	16:41:55.010680 +0800	WeChat	UNIX error exception: 17
default	16:41:55.011005 +0800	WeChat	0x60000026fc00 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	16:41:55.012263 +0800	WeChat	UNIX error exception: 17
default	16:41:55.012574 +0800	WeChat	UNIX error exception: 17
default	16:41:55.012758 +0800	WeChat	UNIX error exception: 17
default	16:41:55.013011 +0800	WeChat	UNIX error exception: 17
default	16:41:55.013154 +0800	WeChat	UNIX error exception: 17
default	16:41:55.013226 +0800	WeChat	0x600000273100 opened /Users/linuxfish/Library/Keychains/login.keychain-db: 580316 bytes
default	16:41:55.095064 +0800	WeChat	startNotifier return: 1
default	16:41:55.202027 +0800	WeChat	Failed to connect (delegate) outlet from (AppDelegate) to (AppDelegate): missing setter or instance variable
default	16:41:55.295249 +0800	WeChat	<WORKFLOW>: init sdk[2.1.2] with appid[com.Tencent.JietuFramework] in the bundle [com.Tencent.JietuFramework] on the device[x86_64, Mac OS X 10.12.5(16F73)]
default	16:41:55.296420 +0800	WeChat	<WORKFLOW>: sdk install signal handler success, exception handler success
default	16:41:55.301665 +0800	WeChat	<WORKFLOW>: sdk send an request to server[http://monitor.uu.qq.com/analytics/rqdsync] with 530 and data[4935] for com.Tencent.JietuFramework, com.Tencent.JietuFramework[2.3.0(9359)]
default	16:41:55.303512 +0800	WeChat	*** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
default	16:41:55.313366 +0800	WeChat	Faulting in NSHTTPCookieStorage singleton
default	16:41:55.313391 +0800	WeChat	Faulting in CFHTTPCookieStorage singleton
default	16:41:55.313405 +0800	WeChat	Creating default cookie storage with process/bundle identifier
default	16:41:55.315813 +0800	WeChat	0x60800027af80 opened /Library/Keychains/System.keychain: 55920 bytes
default	16:41:55.320588 +0800	WeChat	TIC TCP Conn Start [1:0x608000193c10]
default	16:41:55.322656 +0800	WeChat	TIC TCP Conn Event [1:0x608000193c10]: 1 Err(0)
default	16:41:55.322690 +0800	WeChat	TIC TCP Conn Connected [1:0x608000193c10]: Err(0)
default	16:41:55.322870 +0800	WeChat	TIC Enabling TLS [1:0x608000193c10]
default	16:41:55.329511 +0800	WeChat	TIC TCP Conn Start [2:0x6000003897f0]
default	16:41:55.330482 +0800	WeChat	TIC TCP Conn Event [2:0x6000003897f0]: 1 Err(0)
default	16:41:55.330507 +0800	WeChat	TIC TCP Conn Connected [2:0x6000003897f0]: Err(0)
default	16:41:55.452298 +0800	WeChat	TIC TLS Event [1:0x608000193c10]: 2, Pending(0)
default	16:41:55.452616 +0800	WeChat	TIC TLS Event [1:0x608000193c10]: 11, Pending(0)
default	16:41:55.452949 +0800	WeChat	UNIX error exception: 17
default	16:41:55.453189 +0800	WeChat	UNIX error exception: 17
default	16:41:55.453835 +0800	WeChat	TIC TLS Event [1:0x608000193c10]: 12, Pending(0)
default	16:41:55.453875 +0800	WeChat	TIC TLS Event [1:0x608000193c10]: 14, Pending(0)
default	16:41:55.456561 +0800	WeChat	TIC TLS Trust Result [1:0x608000193c10]: 0
default	16:41:55.500513 +0800	WeChat	TIC TLS Event [1:0x608000193c10]: 20, Pending(0)
default	16:41:55.500806 +0800	WeChat	TIC TCP Conn Event [1:0x608000193c10]: 8 Err(0)
default	16:41:55.500838 +0800	WeChat	TIC TLS Handshake Complete [1:0x608000193c10]
default	16:41:55.565279 +0800	WeChat	*** -[NSKeyedUnarchiver initForReadingWithData:]: data is NULL
default	16:41:57.298065 +0800	WeChat	<WORKFLOW>: sdk send an request to server[http://monitor.uu.qq.com/analytics/rqdsync] with 510 and data[206] for com.Tencent.JietuFramework, com.Tencent.JietuFramework[2.3.0(9359)]
default	16:42:00.305359 +0800	WeChat	TIC TCP Conn Start [3:0x610000193660]
default	16:42:00.306548 +0800	WeChat	TIC TCP Conn Event [3:0x610000193660]: 1 Err(0)
default	16:42:00.306566 +0800	WeChat	TIC TCP Conn Connected [3:0x610000193660]: Err(0)
default	16:42:00.622422 +0800	WeChat	TIC TCP Conn Cancel [3:0x610000193660]
default	16:42:00.622564 +0800	WeChat	TIC TCP Conn Destroyed [3:0x610000193660]
default	16:42:17.539266 +0800	WeChat	Failed to connect (helpButton) outlet from (MMLoginQRCodeViewController) to (NSButton): missing setter or instance variable
default	16:42:17.539413 +0800	WeChat	Could not connect action, target class MMLoginQRCodeViewController does not respond to -showScanningHelp:
default	16:42:31.264773 +0800	WeChat	[SafePerformObject] obj <MMResourceService: 0x600000443330>  key 0x600000443330 inQueueTime 4371789106293215, sel checkAndReloadDownloadTask inQueueTime 4371789106304411
default	16:42:31.311360 +0800	WeChat	Failed to connect (settingButton) outlet from (MMMainViewController) to (NSButton): missing setter or instance variable
default	16:42:31.477132 +0800	WeChat	Failed to connect (containerView) outlet from (MMChatsViewController) to (NSView): missing setter or instance variable
default	16:42:31.866524 +0800	WeChat	Failed to connect (tableView) outlet from (MMView) to (MMTableView): missing setter or instance variable

**Comment by TKkk-iOSer** [comment]
谢谢，这个log还是看不出什么问题…把一些可能会崩溃的问题给修复了，请重新clone & install @cs50Mu @bruceCzK

**Comment by cs50Mu** [comment]
@TKkk-iOSer 辛苦啦，我再测试一下，有问题再跟你反馈~

**Comment by gzb001** [comment]
开启自动回复立即崩溃

**Comment by TKkk-iOSer** [comment]
开启自动回复崩溃指的是打开自动回复窗口就崩溃 还是 指有好友发了包含关键字消息的时候崩溃？
另外 mac OS 版本与微信版本分别是多少？
之前有人反馈 mac OS 是 10.11.6 好像会崩溃。可能是系统原因。

**Comment by gzb001** [comment]
mac OS 是 10.11.6 
开启自动回复就崩溃，然后只能重新开启微信。

**Comment by TKkk-iOSer** [comment]
@gzb001 下载一下这个，[WeChatPlugin-MacOS-develop](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/tree/develop)，看看还会不会崩溃。
