### ISSUE TITLE
安装的wechat客户端是最新的Version. 2.3.20，但是插件不支持怎么办？

### ISSUE THREAD

**Issue by yexiaoyu** [TKkk-iOSer/WeChatPlugin-MacOS#453]
![image](https://user-images.githubusercontent.com/5335425/49202343-3ce99e00-f3df-11e8-9b74-36d70f067492.png)
点击更新，提示更新失败。

**Comment by yangnaihua** [comment]
之前也被坑过，所以，我现在都是在apple store 下载，然后关闭自动更新qpp，不轻易更新新版本的微信。直到插件支持了对应的微信版本

**Comment by zlren** [comment]
更新微信客户端之前一定要确保插件支持新版本

**Comment by ballII** [comment]
不知哪裡有合用的v2.3.19 WeChat可以下載呢？

**Comment by KangYJie** [comment]
https://dldir1.qq.com/weixin/mac/WeChat_2.3.19.18.dmg

**Comment by ballII** [comment]
> https://dldir1.qq.com/weixin/mac/WeChat_2.3.19.18.dmg

謝謝。但不知為何，這版也會在安裝插件後就閃退。（安裝插件前都可正常開啟。我OS是10.10.5。）

**Comment by dddddd1** [comment]
现在  2.3.21  了。。。

**Comment by TKkk-iOSer** [comment]
已更新
