### ISSUE TITLE
很好用的插件，为了防止作者懒癌发作，建议出个付费版本。

### ISSUE THREAD

**Issue by cnlinjie** [TKkk-iOSer/WeChatPlugin-MacOS#454]
就怕使用习惯之后，@TKkk-iOSer  不更新了，这TMD就蛋疼了
建议出个付费版本，鼓励支持跟进微信。
不过这东西随着微信更新而更新，显然很被动，付费可以做成订阅模式，按月或按年收费。
努力和付出，有收获才能长久。

**Comment by xieao100** [comment]
一个月没更新了，估计作者被腾讯请去喝茶了 不更新了

**Comment by cnlinjie** [comment]
@xieao100 这..
一些功能很实用，比如配合Alfred 这个，很实用。
应该可以做。。

**Comment by ydq** [comment]
SplayerX 了解一下，Medis了解一下
并不是针对TK哈，也不反对收费，只是让@cnlinjie 知道收费并不能限制任何人
兴趣开源是一回事，以软件谋生又是另外一回事了，最终还是得看作者自己

**Comment by cnlinjie** [comment]
@ydq  谢谢。
WeChatPlugin-MacOS  跟  SplayerX 和 Medis 还是有点区别的。
WeChatPlugin-MacOS 需要实时跟进微信的版本，除非你不用，否则几乎是强制性的，这对作者来说还是需要耗费一定的精力。
出于鼓励和对这插件的喜欢，希望能更长久一点。
事实上，我更希望的是，微信能重视一些基本功能的易用，比如配合Alfred的搜索。
当然，对拦截撤回的消息这种和微信相悖的功能，官方是完全没有可能了。

**Comment by cnlinjie** [comment]
@ydq  这跟早期的，Linux 下使用QQ网页协议做客户端一样，也是开源的产品，结果是腾讯一而再，再而三的修改协议，对维护人员的热情打击相当大，所以后期也已经夭折。
而腾讯出于自身的考量，也没有打算出一个Linux的QQ客户端，对Linux下的用户来说，是很不幸的。

相同的，Linux 下的微信客户端，也是开源维护，可惜前几天也宣布不再维护了。

**Comment by ydq** [comment]
@cnlinjie 嗯，抱歉，是我理解错了。
很多时候第三方只能做一些锦上添花，还是要看官方的态度和支持情况，比如官方开始封杀起来的话，相信即便是TK有心，单也没办法继续一直做下去，这样对TK的自己估计也是不太好的，毕竟算是灰产（我这里把官方不支持或者反对的都称为灰产），如果官方自己本身比较Open的话，即便是TK不收费，也会有类似的项目诞生，当然不排除TK有更好的想法，所以至少微信插件之类的或者说是TX家的产品的插件，做收费感觉会很难。毕竟腾讯本身就不是一个很Open很友好的公司

**Comment by moonfruit** [comment]
@cnlinjie @ydq 我觉得收费更容易惹来 TX 的打击，说不定还会要求赔偿什么的。我是不建议收费的。但是我觉得软件作者可以开放个 donation 的账号，觉得东西确实好的，可以有途径给作者买杯咖啡什么的。

**Comment by zhangnew** [comment]
最下面有捐赠二维码
https://github.com/TKkk-iOSer/wechat-alfred-workflow/blob/master/README.md

**Comment by cnlinjie** [comment]
@zhangnew 已捐赠了。

**Comment by zhangmoumou** [comment]
发现了这个神器、先试用一下，打算捐给作者20w
