### ISSUE TITLE
XML 解析

### ISSUE THREAD

**Issue by wangliangliang2** [TKkk-iOSer/WeChatPlugin-MacOS#456]
当前项目中 你的 xml 解析 看了下是用你自己的写的一套。
建议：
可以试试 微信自带的XMLDictionaryParser 解析器「在 class dump 后的头文件中」。体验和效率会比你当前的高些。

**Comment by xieao100** [comment]
你拉取一下然后改完传一下吧 作者已经不更新了

**Comment by TKkk-iOSer** [comment]
@wangliangliang2 感谢提醒，已优化
