### ISSUE TITLE
远程控制执行成功了, 希望能返回消息通知

### ISSUE THREAD

**Issue by liangnaisong** [TKkk-iOSer/WeChatPlugin-MacOS#47]

**Comment by TKkk-iOSer** [comment]
消息通知？

**Comment by liangnaisong** [comment]
就是MacWeChat收到指令的时候, 能返回一个微信消息告诉我它收到指令了, 有时Mac休眠了, 断网了, 都没收到消息, 不能确定指令是否执行成功

**Comment by TKkk-iOSer** [comment]
懂你的意思了，是可以返回信息给自己确认收到消息了，然而有的指令没有办法确定是否执行成功，比如控制网易云音乐的。其他的话都可以。

**Comment by miaoxinwei** [comment]
为什么我用指令没有作用呢，隐私也加了

**Comment by TKkk-iOSer** [comment]
@miaoxinwei 请查看 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/42  https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/43

**Comment by TKkk-iOSer** [comment]
@liangnaisong 已加，并添加获取全部指令信息。详情请查看README
