### ISSUE TITLE
Mac微信已经更新到2.3.22 (11865)，请问您的插件需要支持吗？

### ISSUE THREAD

**Issue by bobsam** [TKkk-iOSer/WeChatPlugin-MacOS#471]
如题，不知这个更新对您的插件是否有影响~

**Comment by bobsam** [comment]
经实践，安装了插件后，微信一直崩溃无法打开。

**Comment by QianLongGit** [comment]
是的，安装了插件，微信一直崩溃无法打开，卸载了就可以了

**Comment by 976014121** [comment]
安装了插件，微信一直崩溃无法打开，卸载了就可以了

**Comment by bobsam** [comment]
类似问题 #469

**Comment by andyzpl** [comment]
坐等大佬更新了。感谢大佬

**Comment by smile-magic** [comment]
+1

**Comment by xiebruce** [comment]
+1 现在我不敢更新，害怕错过被撤回的消息 😏

**Comment by dengxiaozhen** [comment]
+1，更新到了 Version. 2.3.22 (11865) 微信无法打开

**Comment by layupbolon** [comment]
+1
卸载插件后就好了

**Comment by Kenmmm** [comment]
+1，更新到最新就打不开了

**Comment by zhuweiyou** [comment]
+1

**Comment by TKkk-iOSer** [comment]
可以查看 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/481

**Comment by xiebruce** [comment]
@TKkk-iOSer 哈哈，还真可以，奇怪，我开始还以为那个backup是以前的版本，但是覆盖后却是新版本，期待大佬解决，我先把答案搬过来：

微信更新后，重新安装WeChatPlugin-MacOS，并分别执行以下两条命令即可解决插件不兼容新版微信的问题：
```
cd /Applications/WeChat.app/Contents/MacOS
mv WeChat_backup WeChat
```
