### ISSUE TITLE
导致微信异常退出

### ISSUE THREAD

**Issue by TestAdmin007** [TKkk-iOSer/WeChatPlugin-MacOS#485]
微信版本: Version. 2.3.22 (11880)
系统版本: Mojave 10.14.2 (18C54)
安装后微信闪退

**Comment by chenxull** [comment]
遇到同样的情况

**Comment by itcodes** [comment]
+1。一样的问题。

**Comment by HoustonDuane** [comment]
+1，Mac 版微信再也打不开了，每次都 crash

**Comment by byrain** [comment]
+1

**Comment by yuchuanxi** [comment]
+1

**Comment by JasonLxj** [comment]
+1

**Comment by hurraypub** [comment]
+1

**Comment by TKkk-iOSer** [comment]
因为最新版本微信更换API，导致安装完之后闪退了。目前比较忙没时间更新，临时解决办法有两种：
* 如果想继续使用最新的微信客户端，那么只能卸载微信小助手，或者重装下最新微信客户端。如何卸载看README.md
* 如果想使用微信小助手的话，那么可以下载之前版本的微信替换下. 旧版本微信官方下载地址：https://dldir1.qq.com/weixin/mac/WeChat_2.3.19.17.dmg
