### ISSUE TITLE
自动回复自己

### ISSUE THREAD

**Issue by catroom** [TKkk-iOSer/WeChatPlugin-MacOS#49]
就是我设置自动回复，假如我发送关键字，自己也收到，这个是特性还是可以设置的，求解

**Comment by TKkk-iOSer** [comment]
请问下是在群聊、私聊、还是自己单独发送给自己的？    
是iOS端发送的，还是mac端发送的？   
请问有pull最新的代码么？

**Comment by catroom** [comment]
原来是手机的，不是mac的，我安卓手机发送嘻嘻，也回复了自己，相当于自动回复在手机发送是有效的，mac没有这种情况

**Comment by TKkk-iOSer** [comment]
具体的操作描述一下。比如设置了什么自动回复，向谁发了消息?

**Comment by catroom** [comment]
例如我手机对我女友发送了关键字“嘻嘻”，不是设置“群回复”，我自己收到你小助手发回来的“嘻嘻哈哈”。就是关键字对自己也生效了，我自己可以也收到自动回复

**Comment by TKkk-iOSer** [comment]
请问有pull最新的代码么，我刚刚试了下没遇到这个问题

**Comment by catroom** [comment]
下载最新的版本是吧？ok

**Comment by TKkk-iOSer** [comment]
是的，新增了正则匹配、修复聊天记录消失的bug
