### ISSUE TITLE
最新版客户端会崩老板

### ISSUE THREAD

**Issue by dm22933** [TKkk-iOSer/WeChatPlugin-MacOS#491]

**Comment by shenyansycn** [comment]
客户端版本号：2.3.22（11880）

**Comment by 1337189261** [comment]
同会崩

**Comment by XWJACK** [comment]
提交了新的PR，修复了2.3.22启动崩溃问题，可以试试。

**Comment by sgricky** [comment]
小白请教怎么使用@XWJACK。

**Comment by marvinguo** [comment]
赶快合并pr,发布新版本吧，就改了2个函数名

**Comment by ysysdzz** [comment]
> 提交了新的PR，修复了2.3.22启动崩溃问题，可以试试。

通知作者给你合并下

**Comment by ysysdzz** [comment]
TKKK作者回复，本次更新微信变动比较大不只是两个函数名而已

**Comment by ysysdzz** [comment]
Tkkk作者回复，他最近比较忙，诸位先用旧版
> 昨晚看了，他没修复对，他只是把登录的那个方法给去了，如果是用他的方法会导致小助手菜单栏点击不了，另外2.3.22的话微信改动的比较多， 登录，登出，消息同步，撤回，表情包导出等等的方法都改了，一时半会没那么快解决。我真的是建议你们别太经常更新微信，如果说新版本微信增加了检测机制，就有可能被封号了。

**Comment by xujipm** [comment]
> 提交了新的PR，修复了2.3.22启动崩溃问题，可以试试。

不能防撤回呢！

**Comment by iTofu** [comment]
关注，先用旧版了。兼容了新版麻烦大佬们@我一声。

**Comment by ZephyrJung** [comment]
看起来老版的下载地址也不行了 :joy:

**Comment by yangnaihua** [comment]
坐等更新

**Comment by XWJACK** [comment]
之前的PR是我仅仅是以为启动的方法名换了，并没有看其他的功能，有的说要兼容老版本，我像既然选择升级新版本，老版本就不用兼容了。
今天看了一下，发现改动实在是有点多，很多的方法名都换了，所以改动成本很大，之前的PR已经关闭，打扰了各位。

**Comment by leon-hw** [comment]
> 之前的PR是我仅仅是以为启动的方法名换了，并没有看其他的功能，有的说要兼容老版本，我像既然选择升级新版本，老版本就不用兼容了。
> 今天看了一下，发现改动实在是有点多，很多的方法名都换了，所以改动成本很大，之前的PR已经关闭，打扰了各位。

你已经够厉害的了，我现在是只好换回2.3.21。
