### ISSUE TITLE
老版本WeChat_2.3.19.18.dmg，我之前下载了，本地还有一份，共享给大家。

### ISSUE THREAD

**Issue by yexiaoyu** [TKkk-iOSer/WeChatPlugin-MacOS#494]
https://pan.baidu.com/s/1XvB4ic9YaxEEm9CU0UifGQ

但是不知道在哪设置不检查微信更新，经常弹出要更新的框？

**Comment by leon-hw** [comment]
2.3.21 (11699) 也是可以正常使用这个插件的，但同样时不时会提示新版本更新。

**Comment by leon-hw** [comment]
安装过新的版本2.3.22后，再装回老版本，发现原来的聊天历史记录没有了，如何解决？
