### ISSUE TITLE
无法更新，挂 VPN 依然无法更新

### ISSUE THREAD

**Issue by Medivhex** [TKkk-iOSer/WeChatPlugin-MacOS#499]
![image](https://user-images.githubusercontent.com/30646114/51081579-572cd080-172e-11e9-92da-b58d2c165105.png)

**Comment by Cat7373** [comment]
这是单纯的网络问题吧

**Comment by TKkk-iOSer** [comment]
@Cat7373  +1

**Comment by TKkk-iOSer** [comment]
@Medivhex  可以使用其他方式更新一下，比如菜单栏-小助手-更新小助手

**Comment by YuyangHYY** [comment]
直接 `cd ~/Downloads && rm -rf WeChatPlugin-MacOS && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git --depth=1 && ./WeChatPlugin-MacOS/Other/Install.sh`，用 `omw`的话，目前是有点问题，开vpn也是没用，直接下载就好了。

**Comment by Xuedingzheng** [comment]
网络问题吧 我就是这么更新的

**Comment by Medivhex** [comment]
> 直接 `cd ~/Downloads && rm -rf WeChatPlugin-MacOS && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git --depth=1 && ./WeChatPlugin-MacOS/Other/Install.sh`，用 `omw`的话，目前是有点问题，开vpn也是没用，直接下载就好了。

好哒，谢谢你
