### ISSUE TITLE
build 不起来。

### ISSUE THREAD

**Issue by leewaycn** [TKkk-iOSer/WeChatPlugin-MacOS#5]
eroor.

**Comment by TKkk-iOSer** [comment]
* 有对微信进行赋予权限么？ `sudo chmod -R 777 /Applications/WeChat.app`

* 如果有的话还不行，那就按照下图中数字的顺序，将`run Script`剪切下来，再试试。
![QQ20170817-094947@2x.png](http://upload-images.jianshu.io/upload_images/965383-cf6f4bec86bc117d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


* 如果还是不行，能否说下 Xcode、macOS 版本信息以及错误的内容截图？

* 或者可以使用 Terminal 执行 ./Other/Install.sh

**Comment by haoxuexiaoyao** [comment]
build没有问题

**Comment by zhuangya** [comment]
@TKkk-iOSer 其实不需要搞 777 呀 `sudo chown -R $(whoami) /Applications/WeChat.app` 就好了。

**Comment by TKkk-iOSer** [comment]
@zhuangya 习惯 777 了，我调整下，顺便完善 shell 脚本。
