### ISSUE TITLE
没法卸载咋回事呢

### ISSUE THREAD

**Issue by olafchou** [TKkk-iOSer/WeChatPlugin-MacOS#50]
<img width="607" alt="2017-09-16 12 14 12" src="https://user-images.githubusercontent.com/19890798/30509045-a9a58952-9ad8-11e7-9fb3-24f8d18ea08b.png">

**Comment by TKkk-iOSer** [comment]
请切换到项目的所在路径，在执行改命令

**Comment by olafchou** [comment]
我不是程序员，不懂咋操作，很抱歉啊

**Comment by TKkk-iOSer** [comment]
哈哈哈，没事

**Comment by olafchou** [comment]
你还没告诉我具体咋操作，哈哈

**Comment by TKkk-iOSer** [comment]
先去下载目录看下是否有下载过该项目，有的话删除，再执行以下命令即可

`cd ~/Downloads && git clone https://github.com/TKkk-iOSer/WeChatPlugin-MacOS.git && ./WeChatPlugin-MacOS/Other/Uninstall.sh`
