### ISSUE TITLE
更新微信2.3.23后不能使用

### ISSUE THREAD

**Issue by chuzhaozhi** [TKkk-iOSer/WeChatPlugin-MacOS#515]
### 问题描述
更新微信后小助手不见了，运行代码报错，和上次更新一样的问题

### 版本

* MacOS Version:10.14.2
* WeChat Version:Version. 2.3.23 (11914)
* WeChatPlugin Version:1.7.5

### 日志
xcode运行报错Command PhaseScriptExecution failed with a nonzero exit code

**Comment by dmcdark** [comment]
所以这次我没升级，明智的选择

**Comment by CodeSaid** [comment]
同2.3.23版本微信，安装了之后看不到小助手

**Comment by besteric** [comment]
同没更新，吸取了上次教训，别追最新版本了，没啥新功能

**Comment by junglegiant** [comment]
我先更新了微信才知道有小助手。。好像我的最新版微信重新安小助手是可以用的，但是無法用alfer功能。找不到輸入框。

**Comment by Nikaidou** [comment]
https://dldir1.qq.com/weixin/mac/WeChat_2.3.22.18.dmg

**Comment by besteric** [comment]
系统自动更新了 2.3.23，重新 install 后发现还是可以正常使用的

**Comment by Jony-Gays** [comment]
商店更新WeChat Version. 2.3.23 (11914) 完成之后重新owm 使用正常。

**Comment by edisonX** [comment]
omw 运行下就好咯

**Comment by edisonX** [comment]
刚刚更新

**Comment by chuzhaozhi** [comment]
已解决
