### ISSUE TITLE
希望支持群聊被@后消息自动post到一个url上实现机器人助手功能

### ISSUE THREAD

**Issue by yuzd** [TKkk-iOSer/WeChatPlugin-MacOS#519]
希望支持被@后消息自动post到一个url上实现机器人助手功能

比如在群聊里面
有人@了我
那么把这个消息作为内容 post 到指定 url上去

url可以配置。

这个功能如果能实现 可以撵杀市面上的各种机器人了。
跪求大佬考虑一下
谢谢

**Comment by yuzd** [comment]
我自己改代码实现了。

**Comment by qiuhuadong2015** [comment]
> 我自己改代码实现了。

你好，我有同样需求，能否指点一下在哪里修改?
