### ISSUE TITLE
可以 判断微信群 消息类型，发送者，然后作出自动回复

### ISSUE THREAD

**Issue by ataouli** [TKkk-iOSer/WeChatPlugin-MacOS#52]

**Comment by TKkk-iOSer** [comment]
可以是可以，但是这样的话就过于复杂了，能够识别内容的只有文本，其他的消息内容无法识别，只是知道该消息为图片、红包之类的。自动回复的设置面板也放不下(增加消息类型的选择)，而且之后可能要加入自动回复联系人选择。发送者的话这个可以加上，之后在自动回复的内容我用个特殊字符来替代好了。
