### ISSUE TITLE
安装后无效果

### ISSUE THREAD

**Issue by jindx0713** [TKkk-iOSer/WeChatPlugin-MacOS#53]
osx 10.11.6
微信2.3.2

**Comment by TKkk-iOSer** [comment]
1. 请问是按照第几种方式安装的？
2. 请问安装过程中是否有输入密码？
3. 如果是懒癌版安装，且没有输入密码，打开`Terminal`，那么再执行`~/Downloads/WeChatPlugin-MacOS/Other/Install.sh`,根据提示输入密码即可。
4. 如果是普通安装，打开`Terminal`，切换到项目路径，执行`./Other/Install.sh`

**Comment by gzb001** [comment]
安装完毕之后，重启微信才能看到的呀！
