### ISSUE TITLE
【需求】发送文字自动转换成图片

### ISSUE THREAD

**Issue by uduse** [TKkk-iOSer/WeChatPlugin-MacOS#533]
## 动机
规避明文聊天信息储存 [news here](https://twitter.com/0xDUDE/status/1101917885100945409)，这不是完美的解决方案，但至少可以大大提高储存成本和检索难度。

## 方式
增加 “以图片发送信息” 选项，如勾选，则文字在发送前会经过 [此类文字转图片工具](https://stackoverflow.com/questions/12499728/create-png-jpg-file-with-commandline-on-mac) 的处理，最后以图片方式发出。也可增加逆向功能（对方以同样插件以图片发送文字，则自动解码），不过也可能被 ZF 利用而转换成明文保存。可以把逆向做得效率特别低或来一定程度规避。

也许也可以在输入法的角度操作，欢迎讨论。

**Comment by TomLiu-GitHub** [comment]
我的消息不值钱

**Comment by xiebruce** [comment]
我的也是不值钱，随便查随便看，真要聊敏感话题还用微信？不是应该用telegram么？
