### ISSUE TITLE
希望添加批量删除当前聊天用户功能

### ISSUE THREAD

**Issue by xiebruce** [TKkk-iOSer/WeChatPlugin-MacOS#54]
我不知道你明不明白我的意思，就是每当我跟某个人聊过天，它就自动在列表里出现，而且我不删除的话，就一直保留，导致聊天列表越来越多人，而且微信从来都没有想过添加个批量删除功能，无论是ios还是mac版都没有，我想删除就超麻烦，因为我不想列表上有这么多人。

**Comment by TKkk-iOSer** [comment]
我懂你的意思，大概就是手机端会跟 mac 端同步，导致最近聊天列表会有很多联系人。想删得一个一个删太麻烦，所以想要有个多选删除的功能。

**Comment by xiebruce** [comment]
是的，就是这个意思，其实也一直觉得微信手机版为什么不做这个功能

**Comment by TKkk-iOSer** [comment]
已加

**Comment by xiebruce** [comment]
谢谢你，不过有bug，我多选后右键选择删除，直接程序崩溃退出了
微信：Version. 2.3.5 (9814)
系统：macOS High Sierra 10.13.1 (17B48)

我已更新到你的最新版本：
~/Softwares/WeChatPlugin-MacOS/Other(master) # git pull  
Already up-to-date.

**Comment by TKkk-iOSer** [comment]
@xiebruce 已修复
