### ISSUE TITLE
微信2.3.24.17

### ISSUE THREAD

**Issue by misakichan** [TKkk-iOSer/WeChatPlugin-MacOS#541]
微信提示新版本2.3.24.17，想问下适配了不，没适配就先不升级了

**Comment by zgr0629** [comment]
适配2.3.24.17的。
以后你可以手动复制一份微信出来，重新打开原有微信更新新版本，关掉，再命令行运行omw，更新小助手，然后打开新版本微信自己验证一下能否适配，不行就撤回。

**Comment by iszhuzhi** [comment]
经历：刚更新了，小助手其他功能一切正常，唯一无法使用的就是无法多开第二个微信

已退回老版本微信

**Comment by xifengxx** [comment]
也是一样的问题，更新后，就无法多开第二个微信了

**Comment by WLyKan** [comment]
更新了最新版本的微信，我没装这个小助手，document里也出现里MMappedKV目录

**Comment by aetherwu** [comment]
Version 2.3.24 (12222)
原生浏览器打开网页已失效
