### ISSUE TITLE
撤回自己的消息

### ISSUE THREAD

**Issue by waitingsnow** [TKkk-iOSer/WeChatPlugin-MacOS#55]
现在防撤回功能，会连自己撤回的消息都拦截住，太尴尬了，能否添加一个识别自己撤回消息的功能，就别拦截了。

**Comment by TKkk-iOSer** [comment]
确实会把自己撤回的消息给拦截，我觉得这样挺好的，忘了自己撤回什么还可以看下，移动端的话不会有影响。如果不想看到自己撤回的消息的话，可以使用快捷键`command + t`先关闭下之后再打开。
