### ISSUE TITLE
只要一点，远程控制 Mac OS，微信就直接退出了

### ISSUE THREAD

**Issue by luanwulin** [TKkk-iOSer/WeChatPlugin-MacOS#56]
macbook 15寸的，10.11.6的系统，微信是2.3.1的版本。问题出在哪里呢

**Comment by TKkk-iOSer** [comment]
下载一下这个，[WeChatPlugin-MacOS-develop](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/tree/develop)，看看还会不会崩溃。

**Comment by luanwulin** [comment]
可以了，多谢

**Comment by TKkk-iOSer** [comment]
ok
