### ISSUE TITLE
要是项目没问题的话，是不是可以fork一份过来，继续更新呢？

### ISSUE THREAD

**Issue by cuiyu8580** [TKkk-iOSer/WeChatPlugin-MacOS#563]
我觉得这个插件实在是好用，作者写的代码也非常nice，要是项目没什么问题的话，是不是可以fork一份，继续更新？

**Comment by wdkGitHub** [comment]
挺好的插件，不知道为啥就删库了。

**Comment by cuiyu8580** [comment]
不知道啊，要是不用被请去喝茶，我可以把那个小问题都修修补补，适配一下微信，还能继续用

**Comment by bingo982426** [comment]
旧版本微信还是可以使用的

**Comment by jyrwm** [comment]
问题来了旧版本微信怎么下

**Comment by cuiyu8580** [comment]
@jyrwm 不用下啊，我可以下午更新一下，适配一下新版本，并且把不能用的功能小小修复一下
