### ISSUE TITLE
这个插件会收集个人信息，腾讯都发公告了

### ISSUE THREAD

**Issue by LuckyMango** [TKkk-iOSer/WeChatPlugin-MacOS#564]
请那些蒙蔽在鼓里的童鞋们自己好好去看看。
https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398
![image](https://user-images.githubusercontent.com/43702671/56786745-8c1be980-682c-11e9-977d-b2749e106cc9.png)

**Comment by TKkk-iOSer** [comment]
也请你自己好好去看看 。
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/410   
![image](https://user-images.githubusercontent.com/11961989/56787684-e1a5c580-682f-11e9-9d1e-f031f374808a.png)

**Comment by Chairo** [comment]
我的理解这个只是开了一个web站点，给Alfred当做接口使用。
毕竟两个应用之间交互需要一些手段。
只是这个端口被腾讯说可以用DNS篡改方式可能泄露个人数据而已，TK本人并没有使用这种手段。
可以算一个bug，不是所有人都具备各种攻防知识，修复了就完事了。
不要断章取义。

**Comment by TestAdmin007** [comment]
其实我只用了微信多开功能而已, 其实自己心里都有一杆称

**Comment by colorfuldust** [comment]
> 其实我只用了微信多开功能而已, 其实自己心里都有一杆称

所以只是多开没用其他功能的话会泄露个人信息么

**Comment by TKkk-iOSer** [comment]
> > 其实我只用了微信多开功能而已, 其实自己心里都有一杆称
> 
> 所以只是多开没用其他功能的话会泄露个人信息么

我再解释下吧，正如 @Chairo 所说的， 为什么会出现这个漏洞 ？
初衷是为了给 alfred 提供接口(最近聊天列表、用户搜索、用户聊天记录等)，所以本地通过 GCDWebServer 创建了个服务器，但是没有对外映射，只能够自身的电脑访问（之前有自己测试了一下局域网访问macbook的的这个服务器，无法访问）。(其中一个接口是 http://127.0.0.1:52700/wechat-plugin/user
之后 em 联系我说发现了这个漏洞，也算是我的疏忽，然后就给修复了，当时是去年10月份的时候。
后来觉得可能很大一部分人没有使用 alfred 或者是担心还存在风险，所以我就在 1.7.3 版本的时候把 aflred 的开关给提供出来，在菜单栏->微信小助手-小助手->开启 Alfred 功能 里面可以看到。
![image](https://user-images.githubusercontent.com/11961989/56944741-221a8180-6b57-11e9-9b7a-0b8e1f07df74.png)
这个开关的话默认是关闭的，就是说如果没有去打开这个开关，本地访问 http://127.0.0.1:52700/wechat-plugin/user 是无法访问的。也没法使用 Alfred 的功能。
最后总结下，1. 这个漏洞2018年10月14号的时候已经修复，2.我在1.7.3版本（2018年10月26号）默认关闭这个接口的访问，除非你使用 Alfred + 微信小助手的功能。
