### ISSUE TITLE
各位看过来, 我将继续维护这个项目!

### ISSUE THREAD

**Issue by MustangYM** [TKkk-iOSer/WeChatPlugin-MacOS#565]
https://github.com/MustangYM/WeChatExtension-ForMac

**Comment by raochuan** [comment]
加入一起维护，qq群 号： 229555512

**Comment by YongyouCloud** [comment]
已经在用`https://github.com/Sunnyyoung/WeChatTweak-macOS`了,功能少一些,但是不闪退,主要的多开和防撤回功能都有

**Comment by MustangYM** [comment]
> 在已经用`https://github.com/Sunnyyoung/WeChatTweak-macOS`了，功能少一些，但是不闪退，主要的多开和防撤回功能都有

已知的闪退都修复了

**Comment by TomLiu-GitHub** [comment]
经测试,很多闪退并没有修复.

> > 在已经用`https://github.com/Sunnyyoung/WeChatTweak-macOS`了，功能少一些，但是不闪退，主要的多开和防撤回功能都有
> 
> 已知的闪退都修复了

**Comment by MustangYM** [comment]
> 经测试,很多闪退并没有修复.
> 
> > > 在已经用`https://github.com/Sunnyyoung/WeChatTweak-macOS`了，功能少一些，但是不闪退，主要的多开和防撤回功能都有
> > 
> > 
> > 已知的闪退都修复了

能具体描述一下bug吗
