### ISSUE TITLE
希望可以增加防止撤回人的消息通知！

### ISSUE THREAD

**Issue by xieao100** [TKkk-iOSer/WeChatPlugin-MacOS#58]
撤回没有通知提示，只有打开聊天窗口才可以发现有消息被撤回了！
顺便，求一下QQ版本的小助手！只需要聊天撤回即可！多谢大神！

**Comment by TKkk-iOSer** [comment]
这个没必要吧…我平时也都开勿扰模式哈哈哈。QQ版本的话之前做过，github上面也有别人写的，可以去搜下，不过聊天记录应该会消失，还有文档文件夹会出现一些账号相关的文件。因为没有进行沙盒路径的处理。

**Comment by xieao100** [comment]
好吧，我有点强迫症，QQ那个我有，但是只提示有撤回，也不知道是谁撤回的，撤回的哪一个消息
