### ISSUE TITLE
Build之后提示Missing file

### ISSUE THREAD

**Issue by elvawyf** [TKkk-iOSer/WeChatPlugin-MacOS#59]
xcode build 之后提示 missing file：.../WeChatPlugin-MacOS/Other/Products/Debug/WeChatPlugin.framework/Versions/A/WeChatPlugin is missing from working copy

要怎么处理呢？谢谢！

----
额，后来我把 .framework 文件手动拖到content文件夹里去了，已经可以使用。

**Comment by TKkk-iOSer** [comment]
ok,如果不想修改源码的话直接使用`./Other/Install.sh`，若想修改源码先`build`，若出现`error`可以先忽略，再`run`试试，再出现error的话再排错。
