### ISSUE TITLE
可以获取加群好友信息并且自动发送欢迎加群信息么？

### ISSUE THREAD

**Issue by haoxuexiaoyao** [TKkk-iOSer/WeChatPlugin-MacOS#6]
通过邀请好友入群实现微信群管理，主要需求：可以发送命令移除好友，加群之后自动欢迎好友加群的信息。

另外可以获取到微信群好友的微信号或者微信群好友列表么？

**Comment by TKkk-iOSer** [comment]
上面的那个之前有做过iOS版的，微信群管理。回头有时间整理下我再发到github好了。
![8358DBF9AF2056D8F5624661362B8172.png](http://upload-images.jianshu.io/upload_images/965383-cb33dfa92a20cd9d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![906A3BACE1A990C155F7164B64530349.png](http://upload-images.jianshu.io/upload_images/965383-1d7c383edc6bf065.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

---

获取微信群好友信息也可以，不过微信群好友列表是什么意思？自己加入的群里面的好友列表么

**Comment by xiyouMc** [comment]
@TKkk-iOSer 可以的。 尽快发出来哦。 么么哒

**Comment by TKkk-iOSer** [comment]
@xiyouMc 居然看到了大佬😂

**Comment by haoxuexiaoyao** [comment]
什么时候发出来啊

**Comment by haoxuexiaoyao** [comment]
就是自己微信群里面的群成员信息，然后存入到数据库。

**Comment by haoxuexiaoyao** [comment]
ios版本的什么时候放出来啊

**Comment by TKkk-iOSer** [comment]
@haoxuexiaoyao 放出来了https://github.com/TKkk-iOSer/WeChatPlugin-iOS

**Comment by haoxuexiaoyao** [comment]
非常感谢可以看看了。

**Comment by xiyouMc** [comment]
@TKkk-iOSer 啊？ 我们认识？ 我一个小菜鸟

**Comment by TKkk-iOSer** [comment]
@xiyouMc 不认识，只是之前看过你的文章
