### ISSUE TITLE
是否可以增加微信自动登陆

### ISSUE THREAD

**Issue by ge2009** [TKkk-iOSer/WeChatPlugin-MacOS#60]
是否可以增加微信自动登陆,不用每一回都进行扫码或者在微信端的确认登陆。

**Comment by TKkk-iOSer** [comment]
这个已经支持了，请勾选菜单栏`微信小助手-免认证登录`，登录过程中不需要进行手机端确认，但是以下几种情况还是需要进行确认或者扫码。

* 第一次登录。
* 手机端控制退出mac端微信登录后。
* mac端在`偏好设置-退出登录`退出之后。

**Comment by TKkk-iOSer** [comment]
自动登录已加
