### ISSUE TITLE
Xcode可以debug吗

### ISSUE THREAD

**Issue by fightingForYou** [TKkk-iOSer/WeChatPlugin-MacOS#64]
我build之后没法run，只能自己手动打开微信，有没有什么方法可以实时debug吗

**Comment by TKkk-iOSer** [comment]
参考下这两个 

* https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/20
* https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/5
