### ISSUE TITLE
请教一下怎么发送图片

### ISSUE THREAD

**Issue by WishWei** [TKkk-iOSer/WeChatPlugin-MacOS#65]
- (id)SendAppURLMessageFromUser:(id)arg1 toUsrName:(id)arg2 withTitle:(id)arg3 url:(id)arg4 description:(id)arg5 thumbnailData:(id)arg6; 
这个方法的图片应该是什么？

**Comment by TKkk-iOSer** [comment]
发送图片的话是这个方法 `- (id)SendImgMessage:(id)arg1 toUsrName:(id)arg2 thumbImgData:(id)arg3 midImgData:(id)arg4 imgData:(id)arg5 imgInfo:(id)arg6;`

**Comment by loufq** [comment]
图片发送失败概率比较高【出现在聊天窗口上传一会后提示发送失败的红圈圈】，测试下来成功率不到40%的感觉

**Comment by JasperYanky** [comment]
@loufq 注意预处理下 NSImage 到 NSData 的时候，使用一个  JPEGRepresentation 方法，就没问题了
 [MMMessageSendLogic sendImageMessageWithImage:]  里面找到的

**Comment by JasperYanky** [comment]
@xiaoxiaodexiaoxie 

`-(void)xxx_sendImage:(NSImage *)image to:(NSString *)toUserName
{
    
    
    
    MessageService *service = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("MessageService")];
    ContactStorage *contactStorage = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("ContactStorage")];
    WCContactData *selfContact = [contactStorage GetSelfContact];
    
    
    NSData *imageData = [image JPEGRepresentation];
    MessageThumbData *thumbData = [image genThumbnailImage];
    
    if (thumbData.data.length  >= 0x8001) {
        thumbData = [image safeThumbnailDataWithSize:CGSizeZero] ;
    }
    
    CGSize size = [image getImageRealSize];
    
    SendImageInfo *info = [[objc_getClass("SendImageInfo") alloc]init];
    
    [info setM_uiThumbWidth:thumbData.thumbWidth];
    [info setM_uiThumbHeight:thumbData.thumbHeight];
    
    [info setM_uiOriginalWidth:size.width];
    [info setM_uiOriginalHeight:size.height];
    
    [service SendImgMessage:selfContact.m_nsUsrName
                  toUsrName:toUserName
               thumbImgData:thumbData.data
                 midImgData:0x0
                    imgData:imageData
                    imgInfo:info];
    
}`

**Comment by loufq** [comment]
@JasperYanky nice ！ 之前用  bestRepresentation

**Comment by wells1013** [comment]
+1

**Comment by vincentTai** [comment]
> @loufq 注意预处理下 NSImage 到 NSData 的时候，使用一个 JPEGRepresentation 方法，就没问题了
> [MMMessageSendLogic sendImageMessageWithImage:] 里面找到的

能否提供下demo
