### ISSUE TITLE
对话框输入exit，关闭微信界面

### ISSUE THREAD

**Issue by zuosc** [TKkk-iOSer/WeChatPlugin-MacOS#68]
没错 我已经走火入魔了。。。

**Comment by TKkk-iOSer** [comment]
还有这种操作…![](http://ww1.sinaimg.cn/bmiddle/6af89bc8gw1f8rcavlq52j203c03ct8k.jpg) 
直接 `command + Q`不是更快😏

**Comment by zuosc** [comment]
有好几次都是，回复对方之后。  直接一个exit发过去。。。然后发现好像不太对

**Comment by TKkk-iOSer** [comment]
看来真走火入魔😂😂
