### ISSUE TITLE
【求助】获取群成员列表的功能

### ISSUE THREAD

**Issue by rocdeng** [TKkk-iOSer/WeChatPlugin-MacOS#70]
看了一下微信的接口，ChatRoomMemberData和ChatRoomMemberInfo应该是可以去到群成员的详细信息的，不过不知道可以通过hook哪个函数能够拿到ChatRoomMemberData这个接口，希望大神能够帮忙看看，多谢！

**Comment by TKkk-iOSer** [comment]
直接相关的类是`MMChatMemberListViewController`，方法的话自己摸索吧，你行的。

**Comment by rocdeng** [comment]
我一直以为是ChatRoomMember相关的……
多谢指点，我去尝试下 ：）

**Comment by JasperYanky** [comment]
@rocdeng 请问解决了么
