### ISSUE TITLE
英文系统下面，不能通过defaults write 命令更改中文微信语言了

### ISSUE THREAD

**Issue by doio** [TKkk-iOSer/WeChatPlugin-MacOS#72]
微信还是中文用的舒服，
就在安装好英文系统以后，使用了 defaults write com.tencent.xinWeChat AppleLanguages "(zh_CN)"
 来更换微信的语言，使用了助手以后这个命令就无效了，请问该怎么解决

**Comment by TKkk-iOSer** [comment]
先执行
` sudo defaults write ~/Library/Preferences/com.tencent.xinWeChat.plist AppleLanguages "(zh_CN)"` ，
再执行`sudo chmod 777 ~/Library/Preferences/com.tencent.xinWeChat.plist `即可。
期间需要输入密码
