### ISSUE TITLE
[求助]如何获取图片

### ISSUE THREAD

**Issue by loufq** [TKkk-iOSer/WeChatPlugin-MacOS#74]
如何获取微信聊天记录里的缩略图以及原始图

**Comment by TKkk-iOSer** [comment]
主要的类：`MMChatManagerDetailViewController`  方法：`- (void)onPhotoClicked:(id)arg1;`,这个是点击**查看聊天内容**-**图片与视频**的方法，你可以用 hopper 看下实现。
