### ISSUE TITLE
希望能添加“非文本消息“的防撤回功能🙏

### ISSUE THREAD

**Issue by SparkYuan** [TKkk-iOSer/WeChatPlugin-MacOS#75]
非文本消息->图片、语音之类的

**Comment by ypwhs** [comment]
现在有呀

**Comment by SparkYuan** [comment]
@ypwhs 之前测试过，群里撤回的图片并不能正常显示。也许是因为手机端已经看过消息了，再去电脑端查看，电脑端连上网之后加载的消息比较多（1K+），撤销的图片没能显示出来，我再去核实一下。
