### ISSUE TITLE
打开项目当前目录时出现command not found

### ISSUE THREAD

**Issue by yuxiang8801** [TKkk-iOSer/WeChatPlugin-MacOS#79]
就是用Termimal 打开项目当前目录时出现command not found

**Comment by TKkk-iOSer** [comment]
先试试下载当前项目到`下载`目录并解压，在执行` ~/Downloads/WeChatPlugin-MacOS-master/Other/Install.sh`。
如果还是报错的话麻烦复制`Terminal`的所有信息，这样比较好排错。

**Comment by jyrwm** [comment]
问一个很笨的问题  小助手如何更新   重新安装吗？

**Comment by TKkk-iOSer** [comment]
@jyrwm 需要
