### ISSUE TITLE
图片怎么获取？

### ISSUE THREAD

**Issue by kimpeng** [TKkk-iOSer/WeChatPlugin-MacOS#8]
请问图片应该怎么获取呢？确切点说应该是应用分享的图片怎么获取，msgType为49的。

**Comment by TKkk-iOSer** [comment]
这个没试过，看了下`[MMImageMessageMgr -getOriginalImageWithMessage:]`这个方法里面将`MessageData` 转换成`NSImage`的，你可以用hopper看下里面的实现。有可能在里面。

**Comment by kimpeng** [comment]
谢谢回复！我试一试。
