### ISSUE TITLE
能否基于免验证登录再加上一个自动登录呢？

### ISSUE THREAD

**Issue by new88888** [TKkk-iOSer/WeChatPlugin-MacOS#80]
RT，因为现在已经有了免验证登录，如果打开微信App的时候直接自动登录的话行不行？懒癌懒得再移一下鼠标或者把手放到键盘上回车一下= =

另外微信 For Mac版在1.0的时候是可以直接在Mac更改个人资料的，例如名字 头像 个性签名。地区是不支持，似乎这个功能还没有彻底砍掉 只是入口没了，所以这个功能有可能通过这个插件做回来么？？准确的来说好像是重新挖出入口。账号密码登录也一样 好像之前有人也挖过2.0+的微信，只是砍掉了入口 = =

**Comment by TKkk-iOSer** [comment]
* 自动登录的话之前有考虑过，只是考虑到一种情况就是打开微信，并不想登录之前的账号而是想登录另一个账号，所以就没有自动登录，让用户自己选择是否登录另一个账号(~~按下回车键其实也还好啦hhhh~~)

* 修改个人资料的话我觉得使用率很低吧，真想修改的话拿起手机改下也没事。

* 账号密码登录的其实一开始是打算做，然而在开发的时候发现不仅砍掉了入口，连接口都限制了不能用账号密码登录，用官方的2.0+微信也不行，所以就放弃了。我想如果可以登录的话，那么估计会导致手机上的微信退出，当然只是猜测。

**Comment by TKkk-iOSer** [comment]
自动登录已加
