### ISSUE TITLE
如何迁移mac中的聊天记录？

### ISSUE THREAD

**Issue by DearTanker** [TKkk-iOSer/WeChatPlugin-MacOS#82]
先前微信多开采用的是改包名重签的方式，比如官方叫com.tencent.xinWeChat，那分身就叫com.tencent.xinWeChat1。

现在的问题是，com.tencent.xinWeChat1中产生的聊天记录数据即使整份都拷贝到com.tencent.xinWeChat对应的位置中，在登录原版微信的时候会出现以下情况：

1、迁移数据后的首次登录会提示“繁忙”错误。
2、再次登录可以登录成功，但聊天记录不会加载出来。查看com.tencent.xinWeChat中的数据文件夹会发现被「重置」了。

有什么办法可以把com.tencent.xinWeChat1中的聊天记录转移回原版呢。

「关于聊天记录数据」

每登录一个微信都会生成一个类似名称“0bce90803ca25faf2e2d15c9f588e0a7”的文件夹，从里面的内容来看应该是用来存放这个微信号数据无疑。

**Comment by TKkk-iOSer** [comment]
我觉得应该是没有把所有数据都拷贝吧，原生的微信数据地址：`~/Library/Containers/com.tencent.xinWeChat/Data/Library`，修改后的微信数据地址：`~/Library`，对比下原生的微信数据有哪些，再从修改后的微信数据全部给替换至原生的地址。

**Comment by DearTanker** [comment]
原生的微信数据地址：~/Library/Containers/com.tencent.xinWeChat/Data/Library
修改后的微信数据地址：~/Library/Containers/com.tencent.xinWeChat1/Data/Library

和原生的对比就是多了0bce90803ca25faf2e2d15c9f588e0a7这个文件夹的数据（2个）。
把这2个文件夹复制到原生的微信数据地址中。也是不行的。感觉微信数据是有识别路径，如果路径不同就会读取失败。

之前在Windows下面也是遇到这个问题。如果把旧微信安装的旧数据目录整个拷贝至新微信安装的新数据目录也是无法读取到里面的信息的。当然，登录的是同一个微信号。

**Comment by TKkk-iOSer** [comment]
感觉这就涉及到微信使用的数据库存取的问题了，之前的话是我是直接覆盖掉就ok了，不过没办法让2个微信的聊天记录都保存。不过之前我修改之后是没有保存在沙盒里，而是保存在用户目录下的。不一样的地方是我的bundle id 还是com.tencent.xinWeChat。而你的这个是com.tencent.xinWeChat1，有可能是这个的原因导致生成的生成了不一样的key，也就是多了`0bce90803ca25faf2e2d15c9f588e0a7`，个人猜测。

**Comment by DearTanker** [comment]
0bce90803ca25faf2e2d15c9f588e0a7是和微信号有关系的。同一个微信号不管是bundle id是什么，都会生成类似0bce90803ca25faf2e2d15c9f588e0a7的文件夹。

**Comment by TKkk-iOSer** [comment]
那感觉只有一种解释了，微信的聊天记录读写跟bundle id有关，所以才会导致不同的bundle id聊天记录无法读取。如果只是标示在plist文件里面的话倒还好，修改下就行，就怕是在代码里面进行匹配那就麻烦了，只有hook了

**Comment by DearTanker** [comment]
从windows版的情况看，是跟路径有关可能性更大。
