### ISSUE TITLE
免认证登录不显示聊天记录

### ISSUE THREAD

**Issue by Bay0net** [TKkk-iOSer/WeChatPlugin-MacOS#83]
如果没开启免认证登录，就可以显示聊天记录，使用免认证登录功能的时候所有聊天记录都是空的。
请问如何解决这个问题呢？

**Comment by TKkk-iOSer** [comment]
我这边不会出现这情况，应该不是免认证导致的。去看下设置面板`退出时保留聊天记录`是否打开。

**Comment by Bay0net** [comment]
我把`退出时保存聊天记录`开启了，但是还是出现上述问题，开启免认证的话，登陆之后聊天记录就是空的，关上免认证就可以了。刚刚把微信卸载了，我重新安装试试。

**Comment by Bay0net** [comment]
重新安装了微信，然后下载了1.4.0版本，安装之后问题解决了。谢谢你。

**Comment by TKkk-iOSer** [comment]
nice
