### ISSUE TITLE
有没有windows版本的？

### ISSUE THREAD

**Issue by uncle-link** [TKkk-iOSer/WeChatPlugin-MacOS#84]
windows下也要每次扫码，作者什么时候开发windows版本呢？还有就是mac的这免登的思路是什么呢？有没有介绍呢？

**Comment by TKkk-iOSer** [comment]
windows的话没有…免登的思路是在用户退出的时候，会把一些认证消息给清除了，这时候hook，不让微信把认证信息清除就行了。

**Comment by uncle-link** [comment]
多谢！
