### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by gaoryrt** [TKkk-iOSer/WeChatPlugin-MacOS#89]
自动通过好友请求
请求自动通过后发送欢迎语

能够开放一些 api 么，例如发送文本消息、图片消息、表情包，或者是获取联系人列表、修改备注之类的？

**Comment by TKkk-iOSer** [comment]
目前的话，没打算加这两个功能，没时间。另外关于开放api，之前有人提到，只是这些工作量挺大的，其实关于界面上的设计不好设计。
