### ISSUE TITLE
如何免認證登陸第二個微信？

### ISSUE THREAD

**Issue by klaek** [TKkk-iOSer/WeChatPlugin-MacOS#91]
我有兩微信，平常工作和私人，發現雙開的功能很好。
就是雙開完之後退出，再打開微信的時候，可以直接免認證登陸“最後一個關閉的微信號”
然後再雙開第二個微信，就顯示要掃碼了。

**Comment by TKkk-iOSer** [comment]
这个的话，目前没办法解决，之后想想有无其他解决方案。
