### ISSUE TITLE
希望可以在撤回消息里面加上拦截的那个人，谢啦

### ISSUE THREAD

**Issue by StriveCheng** [TKkk-iOSer/WeChatPlugin-MacOS#92]
如题

**Comment by TKkk-iOSer** [comment]
其实已经有了，你如果看到群聊里面撤回消息里面没有撤回人的信息，那就是你把这个群聊屏蔽了。之后在完善下

**Comment by zhuSilence** [comment]
能取消自己的撤回拦截吗？就是自己撤回的时候。。就真的撤回了，自己的电脑上也不要显示了

**Comment by TKkk-iOSer** [comment]
@zhuSilence 这个的话，你可以先手动关闭防撤回功能，在进行撤回。
