### ISSUE TITLE
autoReplyWithMsg 获取联系人返回 nil

### ISSUE THREAD

**Issue by ygzzhou** [TKkk-iOSer/WeChatPlugin-MacOS#96]
WCContactData *msgContact = [contactStorage GetContact:addMsg.fromUserName.string];
在本机测试返回 nil，可以考虑用
MMSessionMgr *sessionMgr = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("MMSessionMgr")];
WCContactData *msgContact = [sessionMgr getContact:addMsg.fromUserName.string];
这种替代
WeChat+hook.m 325行

**Comment by TKkk-iOSer** [comment]
成，话说是什么时候返回nil呢？
