### ISSUE TITLE
有没有可能接入一个类似于gRpc的远程调用服务呢？

### ISSUE THREAD

**Issue by AZLisme** [TKkk-iOSer/WeChatPlugin-MacOS#97]
这样的话就能够方便的使用其他语言调用微信的功能，实现微信bot
（实际上之前的基于web接口的微信bot都基本上被禁用了）

附上grpc objective c版：https://github.com/grpc/grpc/tree/master/src/objective-c

**Comment by TKkk-iOSer** [comment]
这个的话…目前没打算加入
