### ISSUE TITLE
能不能增加有红包的提醒

### ISSUE THREAD

**Issue by hiberabyss** [TKkk-iOSer/WeChatPlugin-MacOS#99]
当某些群里有红包时，能不能弹出个系统窗口提醒下有红包？

Thanks！

**Comment by TKkk-iOSer** [comment]
可以可以

**Comment by hiberabyss** [comment]
Hi @TKkk-iOSer ,

想问下这个功能现在已经添加进去了吗？

Thanks！

**Comment by hiberabyss** [comment]
Hi @TKkk-iOSer ，

我想自己实现下这个功能，想问下怎么判断一个消息是不是红包消息？

Thanks！

**Comment by TKkk-iOSer** [comment]
可以通过 `AddMsg` 中的 `msgType` 来判断吧

**Comment by bigboyq** [comment]
啥时候可以增加红包提醒呢，现在群消息都是免打扰，错过无数
[你收到了一个微信红包，请在手机上查看]
